<?xml version="1.0" encoding="windows-1252" standalone="yes"?>
<!DOCTYPE document [
  <!ELEMENT document   (languageid,fields,page*)>
  <!ELEMENT languageid (#PCDATA)>
  <!ELEMENT fields     (Bron,Datum,agina)>
  <!ELEMENT Bron (#PCDATA)>
  <!ELEMENT Datum (#PCDATA)>
  <!ELEMENT agina (#PCDATA)>
  <!ELEMENT page       (pagenumber,text?,image?)>
  <!ELEMENT pagenumber (#PCDATA)>
  <!ELEMENT text       (#PCDATA)>
  <!ELEMENT image      (#PCDATA)>
  <!ATTLIST image      timestamp CDATA #REQUIRED
                       size      CDATA #REQUIRED>
]>
<document>
<languageid>21</languageid>
<fields>
<Bron>De Groene Amsterdammer</Bron>
<Datum>18880624</Datum>
<agina>8</agina>
</fields>
<page>
<pagenumber>1</pagenumber>
<text>
DE AMSTERDAMMER, WEEKBLAD VOOR NEDERLAND.
No. 574
\
WANDELSTOKKEN,
verbazende keuze, nieuwste soorten, zeer billgke prijzen. AMSTERDAMSCHE
PARAPLUIE-BAZAR.
69 MUINEMUJK 69. 20 HOMXGSPLUIX 20.
Normaalhemden,
Onderbroeken,
Borstrokken enz.
voor Heeren, Dames
en Kinderen
uitsluitend vervaar

digd in de
gerenomeerde door Dr.
G. JAEGER, eenig
geconcessioneerde
Fabriek van
W. BENGER SöHNE, te Stutgart,
TOT DB LAAGSTE PRIJZEN.
Depot van Dr. JAEGEE's Origineele
Normaal-Wolartikelen,
K, F. DEUSCHLE-BENGER,
Kal verstraat. 15 7, Amsterdam.
Eenige Specialiteit in deze Artikelen
in geheel Nederland.
BESCHREVEN DOOR


DP. m TEN BRINK,

Hoogleeraar te Leiden,
is in Folio formaat met Portret en
Facsimile uitgegeven in de
Hedendaagsche Letterkundigen en slechts
een beperkt aantal verkrijgbaar
voor f3.
UITGAVE VAN
TJ. TABT HOLKEMA, te Amsterdam.
e naar buiten gaat

heeft al dikwyls ondervonden, hoe
moeielijk het daar valt de Koffie te
verkrijgen die men gewoon is te gebrui

ken, en hoe lastig en kostbaar het is
zich telkens van huis de Koffie te laten
zenden. Van onze Koffie, gebrand
volgens de methode van Prof. LIEBIG,
kan men voorraad voor 3 a 4 maanden
meenemen en verzekerd z\jn, dat door
deze speciale behandeling de laatste
boon even geurig is als de eerste.
Tal van getuigschriften van eerste schei

kundigen, particulieren en restaurateurs.
Concurreerende prijzen. Monsters op
aanvrage gratis.

ALEI MEIJER &amp; Ge.,
Amsterdam, Singel 280.
Bekroond met de hoogste onderschei

ding op de Voedingsmiddelen-Tentoon

stelling.
AMERICAN PHOTOGRAPHY

(g. jlisgen,

70 Leidschestraat 70.
Artistique Portretten worden in alle
grooten instantanévervaardigd.
Speciale inrichting tot het maken van
KINDERPORTRETTEN. De opname
geschied in 1/40 seconde.
7 Stuivers Editie
VAN
GEKARD KELLER'S

(Europa in &lt;Al zijn

(Heerlijkheid

met 700 Platen.

TTR AAP ProsPectus en Proefaflevering,
f ilanlT alom voorhanden.
J. A.
FABRIKANT VAN
Kunst-Minerale en Medicinale
Wateren. Alle soorten Bronwa

teren, Gemberbier , Limonades
Gazeuses en gebottelde Bieren
in soorten.
Looiersgracht 82.
AMSTERDAM.
w

en
GEVESTIGD TE AMSTERDAM.

Heerengracht 96 bij de Heerenstraat.
Opgericht 1858.

Privaatinstitiaut ter genezing van
Spraakgebreken.

De Ondergeteekende bericht, dat door
hem van heden af voor
Spraakgebrekkigen en Stamelaars een Cursus is
opengesteld, waarin tevens gelegen

heid bestaat het reeds ontvangen onder

wijs te kunnen voortzetten. Zij die aan
dezen Cursus wenschen deel te nemen,
•worden beleefd verzocht spoedig daarvan
kennis te geven, uithoofde slechts een
beperkt aantal patiënten kan worden
geplaatst.
Men vrage het 27ste Openbaar Jaar

verslag dezer Inrichting, waarin door den
Ondergeteekende het ontstaan en het
wezen van het stamelen beknopt be

schreven is.
J. L. KINGMA, Directeur.
DE OUDE VEER,
|
"j
Q
W
WOLFF DE LANGE. !&gt;
,, Stalen worden op aanvrage franco jj
|l) gezonden. L/
IC

o
, Korte Nieuwendijk No. 42,
H Goedkoopste en meest
gesori teerde Magazynen van
Tati&lt;l«rts, IX. W.
Keizerf racM Vl Besreiistr. 300,
AMSTERDAM.
Specialiteit in het plaatsen van
ZUIGKüNSTTANDEN.
141 TT
"Prinsengracht 297 (onderlmis).
Specialiteit in gegarandeerd zuivere NATUUR-BOTER,
van G. W. NIKKELS Gzn. te Deventer. In 1/s vaatjes van circa 20 KG
en - ie vaatjes van circa 10 KG. Tegen marktprijzen.
J JAN KUNEMAN, Agent.
Deze Boter staat onder strenge controle van het Chemisch Laboratorium.
firma KUYT &amp; FABENSBAOH te Amsterdam.
VERSCHENEN:
G-1 D
voor den bezoeker van het Ethnographiscli Museum

van het Koninkl. Zoölogisch Genootschap Natura Artis Magistra,

DOOK C. M. PLETTE WZN., CONSERVATOR.

Het eerste stuk bevat: Australiëen Oceanië, het tweede: Java en het
derde: De Buitenbezittingen. Ieder stukje is a 10 cents apart verkrijgbaar.
uitgave van TJ. VAN HOLKEMA, te Amsterdam.
HEDEN VERSCHEEN:


INTIMITEITEN
BOOR
JAN C. DE VOS.
INHOUD : Zij had het niet vergeten. Geef me nog een zoen. Hoe ik,
Janus Blanus, uit rederijken" ging. 't Is al zes, zeven jaren geleden.
Stoute Vader. Alleen niet voor mij. Een briefwisseling binnenshuis.
Lize. Een bladzijde uit het Amsterdamsche Palingoproer. Het Loterij

briefje. De slip van zijn jas.
Prijs ingenaaid f 2.50. In Prachtband f 2.90.
Uitgave van S. WARENDORF Jr., Amsterdam.
KAHEREEHG.
RENTE VOOR GELDEN a DEPOSITO.

Met n dag vooraf opvragens: l put.
tien dagen l/i
voor langere termijnen op nader over

een te komen voorwaarden.

BEWARING VAN WAARDEN.
volgens Reglement gratis verkrijgbaar.

AMSTERDAM, 23 Juni 1888.

DE DIRECTIE.
De MeHsciie Gonfl- en l\

$F. ELOY",
FABRIEK
VAN
(gouden ea féilveren &lt;§yoaterieën.
KAL VERSTRAAT 72.
ABC
Alphabetische
Reisgids

is verschenen.
De gemakkelijkste Gids voor
eiken reiziger.
Permanente Tentoonstelling
van Monsters van Buitenlandsche Fabrikaten.
Voor H.H. Exporteurs en Groothandelaren dagelijks geopend
van 9 tot 5 uur.
LUDOLPH HAUSEMAM, Amsterdam, OosteMeU-16.
S T A L M O i: » K K IJ. A R BI H E M.

WEERDJESSTRAAT, Hoek Nieuwstraat en Stationsplein,

TEGENOVEB DEN UITGANG VAN HET STATION.

TELEPHOON No. 105. Telegram-Adres: DE RIJK ARNHEM".

Goede en vlugge bediening tegen de tekende l i H ij k e prijzen.
ALLE soorten SCHOEISEL op inaat
vervaardigd tot reëele prijzen.

FR. GAÏZENMBIJER,
20, Westermarkt vis a. vis de
W. Kerk.
Dr. J. A. HES, Brevetó,
TAND-AKTS VAN Z. M. DEN KONING,
Schrijver van onderscheidene
Tandheelkundige Werken,
Eerelid en Lid van verschillende
__ ^geleerde Genootschappen, Ridder
der Orde van de Eikenkroon, bekroond, met
Goud. en Zilv. Medailles van verdiensten enz.
heeft do eer zijne Gebreveteerde
Kunsttanden en Gebitten op rosó amber
basis te annoncceren, binnen den tijd
van vijf uur gereed, met levenslange
garantie. jJezo Kunstgebitten onderschei

den zich gunstig van alle tot heden ge

bezigde, door hunne fraaiheid, lichtheid
en onzichtbaar punt van bevestiging.
Goudvullingen volgens Amerikaansche
methode enz. Advies gratis.
Keizersar.tusscliea KeyiUersgr.euïiizeistr.AA 680
KUYT &amp; FAREJSSBa.CH.
g" Bureau voor Scheikundig en Microscopisch Onderzoek van
5 Levensmiddelen, SUIKER, Handelsartikelen, Fabricaten enz.
l O. Z. VOORBURGWAL 280, over liet Stadhuis, AMSTERDAM.
g PRIJSCOURANT OP AANVRAAG GRATIS.
J. A. HOMEIJER,

Utrectehestraat 22.

Specialiteit in
Porcelein, Kristal, Glas en Aar

dewerk.
Ontvangen eene uitgebreide sorteering i
goedkoope

;TafelserYiezen en jALascastellen.



J. H. SCHREIER &amp; C».,
Opvolgers van ALBEEDINGK THIJM &amp; Co
Haarl. Houttuinen 85/89.
' 'i stootlatiriet van VeidtutzaamJe Levensmiddelen,
j SCHEEPS PROVISIËN, enz.
j Exporteurs naar Oost- en West-Indië.
Opgericht in 17SO.
Deze Fabriek is door toenemende aan

vraag, thans ook \oorBinnenl. Consumptie
ingericht,en wordt den Handel aanbevolen.
In 1883 werd dit Fabrikaat op de INT.
KOL. TENTOONST. bekr. met de eenige en
hoogste onderscheiding voor dit vak
IstèPrijs (Diplóm'e d'Honneur).
GUENOD, SAÜT1ER &amp; Cl-E, Genêve.
Heden verschenen:

CATALOGUS DER SCHILDERIJEN
IN HET

RÖtsiseum te Amsterdam,
DOOK
A. BREDIUS
Derde geheel omgewerkte druk,
voorzien van 24 nieuwe houteneden.
Prijs f i ing., f l .50 geb.
CATALOGUE DES PEINTURES
DU

MMPP flp Vin ut 3
illuuuöUu l £1 ClL d
PAR
A. BREDIUS
2e dition, entiiTeraent rcfoncluo
avec vingt quatre gravures.
Prijs f 1. geb. / 1.50

uitgaven van T.i. VAN HOLKEMA
te Amsterdam.
e
-rool'
worden hot goedkoopst vervaardigd bij
J. W, F, OFFENBERG,
23 Damstraat, AMSTERDAM.
Volgens een nieuw Systeem.

12 VISITEKAARTJES ƒ 5.
Proeven zijn in de Entree ten

toongesteld.
51,
BOUIjSf
51.
Specialiteit in DAMES-,
HEERENen KINDERSCHOEISEL, van af de
fijnste tot de minste kwaliteiten.
Speciale Inrichting voor gevoelige
en pijnlijke voeten.
REPARATIE'S worden spoedig en
net geefl'ectueerd.
AMSTEBDAMSCHE

| Glazem assclerij &amp; PüiöewasscMng.
Telephoon 1134.
[ Hoofd-Bureau: v. d. Helststraat.
Is door het geheele Rijk te ont

bieden voor het van binnen schoon

maken van Kerken en groote
Gebouwen.
tal: DELI TAFELBIER.
No. l a 13 et. per flesch.
» 2 11
Tevens AMSTEL BEIERSCH a 16 et.
per flesch. GEKSTE LAGER a 11 et.
per flesch, bij

J. VAN DRONGELEN,
Saenredamstraat 18—20
Dr. GOEDKOOP
is te Consulteeren
van des morgens 10 tot 2 en 's avonds
van 6 tot 8 uur, voor

Chron. en Geheime Ziekten,
Adres: Heerenmarkt No. 6.
'T LOOSJE, Rusland 8.

SLIJTERIJ. PROEFLOKHL,
Handel in Binnen- en Buitenlandse!)
Gedistilleerd, Wijnen eu Bieren.
Prima qualitcil COGXAC a_ /' l.l
per flesch. l&gt;ij O flossclien / 0.75.
Alles vrij aan huis.
Breukbanden.
Instrumenten.
Verbandstofien.
Spuistraat b'h Spui 31G,
Hinkel 1) d Mnut 475,
AMSTERDAM.
Prijs ƒ 2.90,

uitnwmnb voet

LEESGEZELSCHAPPEN.


TectóscKtaiscii LatoratorimL
VAN
N. M. KONING, Technoloog,
Thorbeckeplein 79,
AMSTERDAM.
Tarief op aanvrage verkrijgbaar.
GH^IjS'TIAAN E
Prin&amp;engracht bij de Vijzelgracht,
31 ti z i e li -O rider^vij
LESSEN a /!.—PER UUR.
Stoomdrukkerij Ellerman, Harms &amp; Co , Amsterdam.

</text>
<image timestamp="2002:08:20:12:16:51.00" size="326734">D10001Y7.TIF</image>
</page>
</document>
