<?xml version="1.0" encoding="windows-1252" standalone="yes"?>
<!DOCTYPE document [
  <!ELEMENT document   (languageid,fields,page*)>
  <!ELEMENT languageid (#PCDATA)>
  <!ELEMENT fields     (Bron,Datum,Pagina)>
  <!ELEMENT Bron (#PCDATA)>
  <!ELEMENT Datum (#PCDATA)>
  <!ELEMENT Pagina (#PCDATA)>
  <!ELEMENT page       (pagenumber,text?,image?)>
  <!ELEMENT pagenumber (#PCDATA)>
  <!ELEMENT text       (#PCDATA)>
  <!ELEMENT image      (#PCDATA)>
  <!ATTLIST image      timestamp CDATA #REQUIRED
                       size      CDATA #REQUIRED>
]>
<document>
<languageid>21</languageid>
<fields>
<Bron>De Groene Amsterdammer</Bron>
<Datum>18850621</Datum>
<Pagina>14</Pagina>
</fields>
<page>
<pagenumber>1</pagenumber>
<text>
14
DE AMSTERDAMMER, WEEKBLAD VOOR NEDERLAND.
No. 417
*


-ri
•r
l
t.
dood at once, hèno pijn, no ziek; hij gelukkig. Now me not
maken him kapot, hèaltijd miserabel, swearing en schreeuw
tan die groot pijnl Me hoop, dat Cuban shall word hundred
year. What do vou think massa, did'nt me gel him best in
dal way?'

Jaren verliepen en Cesar zwierf nu hier dan daar; de
plantagepeger was allengs geheel opgegaan in den stoker en langzamerhand
had zich zijn karakter evenzeer gewijzigd. Er was een soort van
onverschilligheid over hem gekomen in plaats van de doorzeltende
kracht, die hem vroeger eigen was. Hij vroeg niets meer aan 't
leven en toch hechtte hij er aan; waarom'? Misschien omdat er
in zijn binnenste nog een weinig hoop bestond, zonder dat hij er
zelf van bewust was. Die wonderlijke factor van de ziel is a!s een
,yonk onder de ascli, ofschoon niemand het ziet, glimt ze verder
en dooft niet uit en het kleinste zuchtje doet haar telkens
op, nieuw ontgloeien; dan verwarmt ze het bijna doodelijk kille ge

moed en onmerkbaar, langzaam maar zeker, wordt ze gevoed
tot' dat plotseling die vonk opflikkert en tot een vlam wordt.
Zoo ging het ook Cesar; de gedachte: s nog nmaal terug naar
Holland'r was op den bodem van zijn ziel bewaard gebleven. Dat
verlangen brandde voort in zijn hart, totdat de omstandigheden
den gloed aanbliezen.
Hij was te Port-Natal met de boot, op welke hij voer, met
zware averij binnengeloopen en werd daar afgemonsterd.
Toe"vattig lag er een Engelsch stoomschip in lading voor Amsterdam;
irien nam volk aan en Cesar rustte niet voor hij, een
stokersplaats was er niet meer, als zoogenaamde »duivelstoejager'' werd
aangenomen.
Hij gevoelde wel met zijn vrij goed natuurlijk verstand, dat
het een hersenschim was welke hij najaagde, hij begreep wel
dat het denkbeeld zijn vrouw te zullen terugvinden bijna waan

zinnig was, waar toch toen hij hoorde dat bij kans had om
nognjaals naar Holland te komen, vergat hij alles voor die eeno
gedachte en scheepte zich in.
1) Cesar hou je van mij; ik hou van jou.
- (Wordt vervolgd.)
WIEUWS VAUT BE WEEK.
Naar w$ vernemen worden HH. MM. de Koning en de Koningin met Prinses
Wilholmüm en gevolg op 28 Juli a. s. op het landgoed Oranje Nassau-oord te Eenkuin
Verwacht. De vorstelijke personen zullen daar tot half September blijven.

De Tweede Kamer hesft het wetsontwerp betreffende bet recht van overgang met
87 tegen 34 stemmen, verworpen. De Katner verwierp eveneens ai t. l van de wet
CP de telephonie met C3 tegen 17 stemmen.
Op verzoek van den minister ia do verdere behandeling van dit ontwerp gesehorst.

Naar wij vernemen is het voorloopig Verslag van de Tweede Kazaer gereed over
de overeenkomst betreffende het auteursrecht.

Mr. A. E. J. Modderman, minister van Staat, oud-minister van justitie, is benoemd
tot raadsheer bij den Hoogen Eaad.

Mr. H. A. Des Amorie van der Hoeven, lid der Tweede Kamer, ia benoemt! tot
lid van den Baad van State.

Voortaan mag de afzonder van een telegwphïschen postwisselinhet biancalandsch
Yerkeer, behalve zijn naam en woonplaats, op de strook van den wissel ook andera
aedadeelingen aan don geadresseerde schrijven; deae worden in de telling van de
woorden begrepen.

Ter gelegenheid van den TOsien lierinneringsdag aan Waterioo werd Donderdag da
banier van de vereeniginR van oud-strijders Xeilf.ffnnd e,: Ormtje, die door het over

lijden van het laatste lid hsefl opgehouden to bestaan, uiet militaire eerbewijzen
van het TVaterloo-plein naar het Stadhuis overgebracht. De banier, benevens" het
•rchief der vereeniging, werden onder het houden van toespraken aan den Burge

meester overgedragen, die ze nnmons da gemeente aanvaardde. Da hsriuneringsilag
Werd o. a. in 's-Gravenhage levendig gehouden door liet ontplooien van het Oranje
anncloek of vadorlandscho driekleur van den toren, het raadjiaia, verschiileude
gebouwen en particuliere woningen.

De hecren Creiier &amp; Kramp, J. G. do Groot J.iain, Bo LcaöLasguna &amp; Moük en
P. 4. Jas, geqaalificoevde coHeuienrs der Staats-lotcrjj alhier, hebben in een adres
de aandacht der tweede Kamer gevestigd op verschillende bezwaren, dio zij hebben
tegou het ontwerp van wet betreITondo «Ie ulaatsloterij en tegen het ontworpen Kon. i
Beslnit, houdende voo; schriften voor de collecten», i

Het TVUlorosparlc is thans door eene flinke brecde klinkerbestrating met den ;
Amstelveensehen weg verhouden, acodat ook rijtuigen dien weg kunnen nemen. ':

De Kamer van Koophandel te liolterdara hoeft een adres gericht aan do T-veede j
Kanier, waarin zij met volle overtuiging het dringend verzoek van beUm;;1iebl&gt;-riden \
ondersteunt, waarbij zy verücbtii.g vragen van de lasten waaronder de nijverheid |
op Java gebukt gaat.

Volgens het jaarverslag omtrent den toestand der gemeen t o ottordam bedraagt }
de bevolking aldaar 100,477 zielen. Geboren werden in l 31 C731 kimVren, lenvi
«331 personen overleden. Ei- hadden 1273 hawelijkeu en 22 echtscheidingen plaats, j
Blijkens het verslag over 1884/85 van de vereeniging De AmlacMscJiooJ te Leeu

warden, telt'dio vereeniging 189 leden, waarvan 21 meer dan ƒ5 'sjaars bedragen.
Totaal bedrag der jaarlyksche bijdragen ƒ 7142.50, waaronder is begrepen een sub

sidie der gemeente, ad ƒ4000, en een subsidie van da provincie, ad ƒ2060.

Da feestelijke- pponing van het nieuwe badhuis te Schevoningen zal plaats hebben
op Zaterdag 4 Juli a. s.; niettemin zal het gebouw reeds op l Juli voor hetpublieU
toegankelijk zijn. Hel programma voor dion dag is nog niet vastgesteld.

Te Maastricht is in een druk bezochte vergadering, die door een zevental
geneesheeven wag belegd, besloten iot het oprichten van een badinricuting. Reeds ia
voor een aanzienlijk bedrag voor dat doel ingeschreven.
Ta Joure eerscht het roodvonk epHemiach.
kwaadaardig karakter aan.
Do ziekte neemt meer en meer een
Een jacht op een weggeloopen vrouw. Na meer dan zeven jaren zoeken
in de Vereenigde Staten van Noord-Amerika is het Johann David Bollen,
een Zwitser, gelukt zijn vrouw, die met zekeren Jacob Meister naar Amerika
doorgegaan was, te High-market, Louis Connty, in den staat New-York,
te ontdekken. Hij was de vluchtelingen door Virginië, Nebraska,
Missouri, Michigan en Ohio fot naar High-market, gevolgd en had daarbij,
van alle middelen ontbloot, dikwijls niet de grootste, ontberingen te kam

pen. Doch hij leefde voor zijn vrouw en de hoop om dit juweel eindelijk
toch terug te vinden, gaf hein kracht alles te verdragen. Toen hij de
vluchtelingen had gevonden, was zyn eerste werk Meister eens flink af ta
rossen. Daarvoor werd hij gevangen genomen. Toen hij evenwel de justitie
de geschiedenis van zijn echtelijk lijden mededeelde, werd hij ontslagen
en Meister wegens bigamie ingerekend. Bollen wil zijn vrouw uaar Zwit

serland terugvoeren.

Een lief kindermeisje. Een voor ouders en kindermeisjes zeer leerzame
geschiedenis is onlangs te Dusseldorf voorgevallen. Een kindermeisje be

vond zich met de aan haar zorg toevertrouwde kleine in een park. waar
zij zulk een belangrijk onderhoud had, dat zij haar kinderwagen ge'.icel
vergat. Toevallig kwam een oom van het kind daar voorbij en zag wat
er gaande was. Zonder dat het meisje iets bemerkte nam hij het kind
uit den wagen en droeg het naar huis. Twee uur later, 'fc klinkt haast
ongeloofelijk, 't is echter een feit, kwam de zorgvolle be waaks ter met
den ledigen wagen, waarin zij nog niöt eens gekeken had, insgelijks thuis
en antwoordo op de vraag: ,,hoe het met het kindje ging", heel opgewekt:
Het slaapt gerust als een engel!" Toen mea haar den ledigen wagen
toonde, wilda het meisje eerst zich gaan verdrinken, doch vergenoegde
zich met aan den haar op de stelligste wijze gegeven raad te voldoen, om
ten spoedigste haar boel te pakken en aich weg te maken.


Het spoelen der bierglazen in bierhuizen. De politie te Erfurt heeft
in de plaatselijke bladen een waarschuwing doen opnemen, dia daar wel
algemeen ter harte mag worden genomen en aan welke wij hopen dat ook
in onze hoofdstad met hare talrijke bierhuizen het oor zal worden ge

leend. Zij luidt aldus: Er is over geklaagd, dat in eenige bierhuizen bij
het spoelen der bierglazen niet de noodige zindelijkheid wordt in acht
genomen en men in een en hetzelfde water een zeer groot aantal glazen
spoelt, zoodat ten slotte de glazen in plaats van schoon gemaakt, ver

ontreinigd worden. Die handelwijze is walgingwekkend en ook niet be

vorderlijk voor het welzijn der betrokken personen. Derhalve richten
wij tot de eigenaars het verzoek, zooveel bij liet spoelen der glazen als
in elk ander opzicht do grootst mogelijke zindelijkheid te betrachten.
Het publiek echter noodigen wij uit tekortkomingen in dit opzicht van
de zijde der waarden, ter kennis van de politie te brengen, en de bier

huizen, waarin dergelijke onzindelijkheden worden opgemerkt, niet meer
te bezoeken.

Een vereeniging van onbestorven weduwnaars. Een Berlijnsch blad
behelsde onlangs de volgende vermakelijke oproeping: Aan de onbestor

ven weduwnaars en dezulken, die het moeten worden, wordt bij deze de
uitnoodiging gericht zich door gezellige aaneensluiting over hun gedwon

gen eenzaamheid te troosten. Het doel der Vereeniging ia het onderhouden
en verheffen van het echtelijk bewustzijn, waarbij tevens het bezorgen
van opwekkend levensgenot niet uitgesloten is. Ieder echtgenoot wordt
aangenomen, die zich met ten minste n trouwring kan aanmelden. De
laatste moet bij de opname aan de Vereeniging gegeven worden en ia
bewaring gegeven aan het bestuur, daar hij voor de eigenaaars gedurende
het zomerseizoen, gelijk de ervaring leert, geen waarde heeft, en slechts
tot onverdragelijke toestanden aanleiding geeft. De leden van de
Voreeeeniging brongen hun vrijen tijd, eu als zij het, begeeren, ook de nachten
in het Hnis der onbestorven weduwnaars" door. Echtgenooten, die kleine
kinderen bezitten zullen hun gewone nachtelijke rustverstoringen, die
kunstmatig op bedriegelijke wijze nagebootst worden, niet behoeven te
missen. Oudere vrouwen vindan in eea bijzonder vertrek een onderko

men, en alles is zoo ingericht dat precies te klokke twaalf door een der
genooten, wien bouii het is, een bedsermoen gehouden werd. Om den
rijperen echtgenoot geen zijner gewoonten te doen ontberen, heeft er
eiken avond ean verbitterde kamp om uen huissleutel plaats. Haeren
die daarbij aan handtastelijkheden gewoon zijn, moeten dit uitdrukkelijk
molden ; voorts zullen de leden in het wederzijdse!! aannaaien v.in afge

rukte knoopen kraoht en troost, vinden en de gemeenschappelijke
oefeningt-n in echtelijke teederheid. en geduld, het echtelijk bewustzijn versterken.
Het vrooiijke levensgenot zal door bet gemeenschappelijk bezoeken van
plaatsen van uitspanning worden verschaft, welke de anders aan zijn hui-?
geketende slechts van hooren zeggen kent; het spreekt van zelf dat,
daarbij slechts onschuldige verstrooiing en natuurbeschouwing in
aannierkinff komen. \Vio betrapt wordt de perkeu te buiten te gaan, zij het in
gedachten, zal iia eeu drievoudige herhaling, uit de vereeniging worden

</text>
<image timestamp="2002:08:18:05:14:47.00" size="281965">D100016E.TIF</image>
</page>
</document>
