<?xml version="1.0" encoding="windows-1252" standalone="yes"?>
<!DOCTYPE document [
  <!ELEMENT document   (languageid,fields,page*)>
  <!ELEMENT languageid (#PCDATA)>
  <!ELEMENT fields     (Bron,Datum,Pagina)>
  <!ELEMENT Bron (#PCDATA)>
  <!ELEMENT Datum (#PCDATA)>
  <!ELEMENT Pagina (#PCDATA)>
  <!ELEMENT page       (pagenumber,text?,image?)>
  <!ELEMENT pagenumber (#PCDATA)>
  <!ELEMENT text       (#PCDATA)>
  <!ELEMENT image      (#PCDATA)>
  <!ATTLIST image      timestamp CDATA #REQUIRED
                       size      CDATA #REQUIRED>
]>
<document>
<languageid>21</languageid>
<fields>
<Bron>De Groene Amsterdammer</Bron>
<Datum>19170519</Datum>
<Pagina>9</Pagina>
</fields>
<page>
<pagenumber>1</pagenumber>
<text>
1 \

»ƒ 19 Mei '17. Np. 2082
DE AMSTERDAMMER, WEEKBLAD VOOR NEDERLAND
,41

v;
v
DE TWEITSCHE BANK

AMSTERDAM. ROTTERDAM. 's-GRAVENHAGE.
•eatert kapitaal f 16.000.000.—. Reaarvsi f 9.850.000.—.
tw vftlto aansprakelijk voor vtrblntentoea vaa:
B. W. BLUDENSTEIN 4 Ct., 65-56 TNreadMêdltttrMt Loata E.C.
B W. BLUDENSTEIN Junior, Easelwdt,
l LEDEBOER A Co., Maal*.
fctokeatec-Cranut met Beit0verg««4iaf.
• !•-«• Twko«pWlM«liop binnen en Buitealand,Tre«BdeMut,CMp«u.
i»«Mue«rütg op Binnen- en Buitenland.
BmbraneretlleteH in Noord- en Zuid-AmerfloL
U-CB Verkoop Effecten.
Xenea TU fielden op Prolongatie met bewaring vu het onderpand
, bfl de Twentsehe Trut Mtj.
BewariBff van Waarden. Safe Deposito.
~ • ' tegen verlies bfl uitloting vaa fondcea.
i op FondMB en Goederen.
aan Handelaren en Indnstrleelea M) kan afdeeltag
CEBIBEEKieiNG, hetzij tegen borgstelling, credlethypotheek
of andere zekerheid, hetzl in blanco.
Rente voor DEPOSITO'S.
pCt
«
n MUM! rast. . . . % pCt. beneden den gemid

delden prolongatie-koers, met eea maximum vu . . 3%
3
3%
•«•Jaar
*)
•) Van den dag dei opzegging af wordt % pCt. minder rente vergoed.
^LEVENSVERZEKERING - BANK
AMSTERDAM
ff
-JlEJ.BOKNÜ\t.AdJ.-tHt DAAtUELTX
Pandbrleven

in omloop:
l Hypotheekbank l
31 Dec. 1914


f2.567.150,Holland • Amerika - Utrecht


pCt. Pandbrieven 9O pCt.

*•••• Verkrijgb. bij alle EFFECTEN- •§•§•••••
31 rvc .mi K l HANDELAREN in stukken vail qt n,P iqifi
il Dec.rl915 • f 1000.-, f 500.-, f 250.-en f ICO.-, l 31 DeC' 1916
f3.529.550.—|^_^M.^__«..M.| f5.649.600,
D: H. PIMENTEL
MAKELAAR IN EFFECCEN
CUJ * 4 Vtrten. t. A. Effttttnhandxl ttfdatt)
AMSTERDAM.,'
froote Koopmensbeurs, Kamers 6-7-8
TM^Bea tnt«rc. Noord 5363 m SS03
KPU-COUUHT ~ ! P«Ol(J)iaTi!
BtlMIIHtlllGVJIIIlUEfFnCTtHMKIII

ADülSIBEiBEI VU VERM06EHS
jCt PaiteTBii
OHTTAHS-eDBETAALKiS

N, Doclenslr. 20-22, Amsterdam,

Kapiüal u hiirnn /
5.500.000,Renteverg. voor gelden h deposito.
met l dag opzegging. . XpCt.
Bedr. tot ƒ 20.000.- terst. betaalb.
met 10 dagen opzegging K pCt.
Voor andere termijnen op nader
overeen te komen voorwaarden.
Open en gesloten bewaargeving
volgens Reglement.
SAFE DEPOSIT INRICHTING,
geopend:
op Werkdagen van 8X tot 5 uur.
op Zaterdagen en
Beursvacantied. van ,8% 2 ,
Loketten van ƒ 2.50 per maand
(ƒ 10.—per jaar) en hooger te huur
voor bij de Directie bekende of
geïntroduceerde personen.
Amsterdam, 2 April 1917.
/^T" DirectX «/.Nederland "
S: MR.ALEX.H.WERT1IEIMWI
3 EN l
*L J.D.N.PISTORiUS • .
Dirkzwager's
Scheepsageiitniir

Maassluis en Hoek van Holland
Opgericht 1872
Belasten zich met het rappor

teeren van schepen en het behan

delen van scheepszaken op den
Nieuwen Waterweg

Nieuwe
Berging
Haal schappij
Maassluis
Opgericht 1887
Contracteeren voor het bergen
van gezonken schepen en ladingen,
op de rivieren en buitengaats; be

lasten zich met het instellen van
duikeronderzoek, enz. enz.
M. PIMENTEL,

Accountant
Leeraar BoekhoudenM.O.
Valerinsstraat 108, Amsterdam.
TELEFOON Zuid 2422.
Standaard HyjoHeeïHaii te Rotterdam
Directie: Mr. H. H. C. Castendijk en
Jhr. H. F. Schuurbeque Boeye
De Bank verstrekt gelden
onder eerste hypothecair ver

band en geen onder
eom*rdle vu het Algemeen
Administratie ea
Trustkantoor 4% 96 PANDBRIEVEN
uit tegen beurskoen.
De HollamUe VnlioM
HAARLEM, JANSWEQ 42.
Bijkantoren: Amsterdam.Damrak 99
Rotterdam, Wflnhaven 129a.
's-Qravenhage, Qed.Burgw^8.
Maastricht; Stationstraat 36.
De Bank verstrekt gelden tot elk
bedrag met een minimum van
f 5OO en verkoopt 4Jf pCt. schuld

brieven in stukken van f 1000,
f500, f 100 en f50.
RotlBypattóMïoorMerlaiiil
Opgericht in 1884
T»lt«ekeii laatsek. lapttaal ƒ 5.QW.OO».
Verstrekt geld op eerste hypo

theek zonder vooruitbetaling van
rente. Voor inl. wende men zich tot
het kantoor der Bank, Oed. Bierha

ven 25 te R'dam of tot hare Agenten
in de hoofdplaatsen des Rfks.
DeDlr. Mr. W. v. ROSSEM, Mr. TH.
REEPMAKER, Mr. N. B. C. v. WIJK.
Vaderlandsche Hypotheekbank - 's-6ravenhage
31

Dec.
1914

1915

1916
Gesloten
Hypothecaire
Leeningen
f 6.401.449.50

- 6.618.749.50

• 7.341.619.50
Ontvangen

Aflossingen
f3.324.481.85

- 3.680.834.85

- 4.103.016.50
Uitstaande
Hypothecaire
Leeningen
f 3.076.967.65

- 2.937.914.65

-3.238.603.
In oml. zijnde
Pandbr. en
Spaarpandbr.
f 3.063.0.95.32

- 3.170.719.865

- 3.499 554.40
Opvraag

baar
Kapitaal
f 900.000.


-•900.000.
- 900.000.
Saldo
Winst- en
Verliesrek.
f 14.968.- f43227.885
-16.020.43

- 21.164.725
Totale

Reserven
- 48.362.99

-50.86569
Divi


dend
Vraagt uitgebreid verslag
Levens Yerzekering-Maatschapp
DORDRECHT"
Vennootschap

DORDRECHTNEDERLAND".
II1

BRANDBEDRIJFS- en
INBRAAK-VERZEKERING.
Voorbeeld van Gemengde Verzekering:

Iemand van 30-jarigen leeftijd sluit een vs rzekering groot
f 10.000.—, betaalbaar op 60-jarigen leeftijd of terstond bij
i vroeger overladen. Hij betaalt daarvoor gedurende 30 jaren
of tot eerder overladen f 260.—per jaar.

CONCURREERENDE TARIEVEN.
Hoofdkantoor te DORDRECHT,
Bijkantoor te AMSTERDAM, Heerengiaclrt No. 495, Directeur L. M. SMITH.
Inspecteur A. J. LHIH IR., Vosmaerstraat No. 4, Amsterdam.
. , 's-GRAVENHAGE, Anna Panlownastraat 52, Directeur M. H. E. SACHSE.
Inspecteur G. BF.RQMAN, Galileistraat 139, 's-Qravenhage.
. . ROTTERDAM, Korte Hoqfdsteeg No. 43 a, Directeur H. BRUCH.
Inspectrice Mej. J. C. TIEMEYER te 's-Gravenhage, Schenkkade 250.
Ook de Agenten en Agentessen verstrekken gaarne inlichtingen.
Solide.en ijverige personen gevraagd als Vertegenwoordigers
Assurantiekantoor

J. Herra, SeliFödep,
Keizersgracht 391
\ Amsterdam.
Telefoon N. 329.
Verzekering van
kunstvoorwerpen
tegen alle schade.
Billijke premiën.
Nsderht&amp;dsch -Indische

Brandwaarborg-M^.
Ojurlclt li 1890.—Berestln te imterdaa.
SLUIT VERZEKERINGEN tegen
Schade door , Brand op
Woon- en Pafthuixen,
Inboedel», VenbUair,
Fabrleken,Etabliaaententen.
Kantoor: Singel 262,Aasterdam.
Kali Be$ar-W«st, Batavia.
{S.I.W VANBUUREN.
M. A. VRIESENDORP.
E.LANKMOUT.
Gemachtigde: NEUMANN &amp; Co,
Batavia.
Nederlandsche Handel-Maatschappij.

Gestort Kapitaal / 60,000,000. Reservefonds / 9,925,432,
Hoofdkantoor: AMBTBBPAM.
Agentschappen U: '••GBAVENHAOE en ROTTERDAM.
Vatiying in hef Oosten: Batavia, Soerabaia, Semarang, Bandoeng, Weltevreden,
CherlDon, TegaL Pekalongan, DJember. Solo, DJokJakarta, TJllatJap,
Padang, Medan, Teblng-Tlnggt (Deli), Tandjong BaleC Kota-Rad|a,
Palembang, Telok-Betong, Pontlanak, Bandjermasln, Makaaier, ftingaporo,
Penang, Rangoon, Hongkong en Snangnai.
In- en Verkoop van Wissels en Telegrafische
Transferten,—Incasseerlngen en Flnancleeringen.—-Schrif

telijke of Telegrafische Credieten. Beiseredieten*
Deposito's. Rekening-Courant. Administratie
van Kftecten en alle andere Bankzaken.

RENTEVERGOEDING VOOR DEPOSITO'S;
JHet 12 maanden opzegging	4 pCU
DE HAARLEKSCHE

HYPOTHEEKBANK.
4 V» % Pandbrieren tegen
Amsterdamschen Beurskoers
WIEftlfEAN'S BAStt
A. M S T B B D A M
GESTORT KAPITAAL EN RESERVE F 5.500.000.
Geeft voorschotten aan hare rekening-houders Belast
zich met alle Bankzaken Uitvoering van Effectenorders

RENTEVERGOEDING TOOR DEPOSITO'S:

met n dag opzegging	1% pCt.
tien dagen ',8ï»
een maand 2
, drie maanden 3
. een jaar 4
SAFE-DEPOSIT
Binnenl. Vaart Risico Sociëteit.

Tilil. 1.10281. gevestigd te A'dam, Rokin 69. Tilif. 1.73211
DIRECTEUREN: Jan A. v. E{Jk, Dr. «I. H. Croockewit
De .B1NNENLANDSCHE VAART RISICO SOCIËTEIT" sluit:
VERZEKERINGEN op alle Binnenwateren van Nederland,
België, Duitschland, FrankrQk, enz.
VERZEKERINGEN op Schepen, Schuiten en Stoom

boot e n.
VERZEKERINGEN op Koopmansgoederen, Huisraad, Inboedels,
enz., geladen in Schepen, Booten, enz.
VERZEKERINGEN1 te LAND door geheel Europa per spoor,
Wagens, enz.
VERZEKERINGEN per POST enz. op Effecten,
Bankpapieren, Edelgesteenten, enz. door geheel Europa,
naar en van Amerika, naar en van Oost- en West-Indien, enz.
VERZEKERINGEN op PASSA01ERSOOEDEREN. De schade
in de Hotels enz. wordt vergoed.
P. POÜWELSJr., Amsterdam,
1877 L,EL,IEeBACHT 45.
Effecten, Voorschotten in
Rekeningf!AnrATlf TEL. 5481.
\jUUiaIlt. m 9423 (Beurs).
RIJNLANDSCHE

Hypotheekbank
TE HAARLEM.


4% /«
PANDBEIETEN
99 %
STUKKEN VAN
/1000.-,/500.-,/100.-.
CREDIETÏEREENI6IH8

OPGERICHT IN 1853

Kapitaal f 5.000.000. Reserves f 1.160.000.

Hoofdkantoor en 2 Bijkantoren te Amsterdam.

14 Agentschappen in het land.

Credieten - Cheques - Incasseeringen -*Safe Deposil.
{met l dag opzegging l pCt.
voor l maand Tast . 2
Smaaudeu vast 2^

Prospectus, Incassotarief en Depositoreglement verkrijgbaar.
01 Provinciale
L Crediet- en Spaarbank!
f" SCHIEDAM
Tegen beurskoers verkrijgb. bij
H.H. Commissionnairs alsmede
ten kantore der Bank in stukken
van f 1OOO.-, f 5OO.—en
flOO.-.
DE
Weekblad voor Nederland
kost slechts f 1.90 per kwartaal
Centraal locountaiits-Kantoor
onder Directie van Mr. I». G-. H. I&gt;OiP
Lid van het N«d«rlandsoh Instituut van Accountants
LICHTEGAAED Ho. 8, TJTBECHT. Tel. 140
NED.-IND. ESGOMPTO MAATSCHAPPIJ

OPGERICHT IN 1857
KAPITAAL
ƒ25,000,000.waarvan uitgegeven en volgestort	15,000,000.
RESERVE	3,000,000.
Hoofdkantoor: B A T A V l A
AGENTSCHAPPEN te: Soerabaja, Semarang, Weltevreden, Padang,
Bandoeng, Cheribon, Macassar, Djokdja, Medan, Tegal

AMSTKKOAM 'a-«RAVKNHA«E
Keizersgracht 573/5 Prins Hendrikplein 14

Voorschotten op Ceelen Incassi op
Indië, Holland en het Buitenland
Open en gesloten Bewaargevingen

RENTE VOOR DEPOSITO'S:

met l dag opzegging 2 pCt. gedurende 3 maanden vast 3 pCt.
10 dagen 2J4 , l jaar vast. . 4 ,
gedurende l maand vast 2Vs
SCHRETLEN &amp;
AMSTERDAM,Sophiaplein2. NIJMEGEN, Stadsgracht,
int.Tel. N 5701 en N 9128. Int.Tel. 1379 en 1701.
Verrichten alle Bankzaken.
Incasso-Bank.
AMSTERDAM - ROTTERDAM - ALMELO - DORDRECHT
Volgestort Kapitaal f 10.000.000
Bosorve f
1,664.000.Effectenorders.
Coupons.
Prolongaties.
Vreemd
BaakCheques, (papier.
Buiten!. Wissels.
GEVESTIGD TE
's-GRAVENHAGE, MOLENSTRAAT No. 39,
geeft 41|2 % Pandbrieven uit in stukken van
f 1OOO,-, f 5OO,—eii f 1OO.—.
m lui
verzekeren ROERENDE en
ONROERENDE GOEDEREN, '
OOGST, TEE, enz. tegen
billijke voorwaarden.
ring
verzekert GEBOUWEN en
GOEDEREN tegen de Schade,
veroorzaakt door STORM
en LEKKAGE.
Gevestigd te OTJDKARSPEL.

WAAB NIET VERTEGENWOORDIGD,
WORDEN ACTIEVE AGENTEN GEVRAAGD.
Heb het uitstekendste aan te bieden dat iemand wenschen kan
hoe zal de wereld het weten, indien gij niet adverteert?
JOHN P. ROCKEFELLER
Raadpleeg voor Belegging en Speculatie

't Financieel Nieuws- en Uitlotingsblad,

verschijnt 2 maal per week, abonnementsprijs ƒ X.5O per Jaar.
Proefnummers op aanvrage kosteloos en franco aan de
bureelen: DEN HAAG, Noordeinde 144 (Postbus 84, Tel. H. 6374)
AMSTERDAM, Heerengracht 154 (Postbus 420, Tel. Centr. 506)

Tevens verkrijgbaar a 5 cent» per nummer bij alle kiosken
en bli eiken spoorwegboekhandel In Nederland.

</text>
<image timestamp="2002:08:23:14:30:12.00" size="374958">D2002WA.TIF</image>
</page>
</document>
