<?xml version="1.0" encoding="windows-1252" standalone="yes"?>
<!DOCTYPE document [
  <!ELEMENT document   (languageid,fields,page*)>
  <!ELEMENT languageid (#PCDATA)>
  <!ELEMENT fields     (Bron,Datum,Pagina)>
  <!ELEMENT Bron (#PCDATA)>
  <!ELEMENT Datum (#PCDATA)>
  <!ELEMENT Pagina (#PCDATA)>
  <!ELEMENT page       (pagenumber,text?,image?)>
  <!ELEMENT pagenumber (#PCDATA)>
  <!ELEMENT text       (#PCDATA)>
  <!ELEMENT image      (#PCDATA)>
  <!ATTLIST image      timestamp CDATA #REQUIRED
                       size      CDATA #REQUIRED>
]>
<document>
<languageid>21</languageid>
<fields>
<Bron>De Groene Amsterdammer</Bron>
<Datum>19050409</Datum>
<Pagina>12</Pagina>
</fields>
<page>
<pagenumber>1</pagenumber>
<text>
l
DE AMSTEKDAMMER WEEKBLAD VOOR NEDERLAND.
Nu 1450
Verkrijgbaar in flesschen &amp;, 50 ets.,
75 ets. en ƒ1.25 bij H.H. Apotheker?
en Drogisten. Let op het merk Anker l

F Ai. RICHTER &amp; Go, Rotterdam.
Ta Amsterdam bij CLÉBAN, Heili

gen weg; VAN TUYLL, Paleisstraat:
l RASSEN, Prinsengr. 246; SANDERS
Roiin 8; SCHUIJT Jr., Haarl.str. 139.
G. J. VAN STEEDEN, J. KOK

STEN J.G.zn., c.s., Makelaars.
zullen op Maandag 17 April
19O5, des avonds na zes uur, in
het Verkooplokaal Frascati", te
Amsterdam, ten overstaan van den
Notaris A. C. SCHWARTZ, in
veiling brengen:
Het WOKELHI'IS, waarin
sedert jaren is uitgeoefend het
Café, gen. De Plantenbeurs",
met twee afzonderlijk verhuurde
Bovenhuizen, Achterhuis en Erve,
te Amsterdam, aan den

SINGEL 449,
nabij den Heiligen w e g, groot
Centiaren.
Te bezichtigen des Woensdags,
Zaterdags en op den Verkoopdag
van 2 tot 4 uur.
J. B. PARIS, H. L. A. HE1JE,
J.P. RIEKEN, S.VAN DEN BERG,
W..C. DEENIK, M. J. SCHWEER
BEY DERBECKE enP.C. BREI K,
Makelaars, zullen op Maandag
17 April 1ÖO5, des avonds na
z&amp;s uur, in het Verkooplokaal
VFrascati," ten overstaan van de
Notarissen H. J. PARIS en P. L.
PIETERSE, in veiling brengen:
Het HEEREXH1DIS,met Ach

terhuis, afzonderlijk verhuurden
Kelder, Open Plaats Tuin en
Erve, te Amsterdam, aan de

Rfguliersgracht 17,
tusschen de Heeren- en Keizers

gracht, groot
Are, 39 Centlaren.
Nog te bezichtigen Dinsdag, Don

derdag en op den Verkoopdag van
2 tot 4 uur, op vertoon van een
toegangsbewijs, onderteekend door
een der gemelde Makelaars.
n' en Terkoop.
Catalogus grata.'
l'HILIPP KOSACK, Berlin, Burgstr. 8.
J. G. J. HOL, J. J. F. F. M
LLER, J. C. P. KNAPP Jr., E.
BLEES ING, J. J. DE WAAL, C.
BOENDERMA.KER, H.
STRADMEIJER en H. B AÜER, Makelaars,
zullen op Maandag 17 April
• 9u&gt;f, des avonds na zes uur, in
het Verkooplokaal Frascati," ten
overstaan van de Notarissen W.
KRANENBURG en H.
MOLENPAGE, in veiling brengen :
No. 1. Het bijzonder gunstig
gelegen
Dubbel Winkel li u is,
met afzonderlijk verhuurd wordende
Boveiihuizen en Erve, te Am

sterdam, aan den

N, Z, Voorburgwal 149,
hoek Paleisstraat.
No. 2. Het eveneens gunstiggelegen
Wiukelhnis en Erve,

PALEISSTRAAT 23,
naast voorgaani perceel.
Deze perceelen zullen na afzon

derlijke veiling bij opbod en afslag
gecombineerd worden in slag gelegd.
Nog te bezichtigen Dinsdag, Don

derdag en op den Verkoopdag van
2 tot 4 uur,
Hoek
Paloisslnial
N. Z. Voorburgwal.

Gegadigden naar de Publieke Vei

ling der Perceelen Paleisslraat 23
en lioek N. X. Voorburgen aJ I4!&gt;, d.d.
17 April a.s., des avonds na zes nnr,
in het Verkooplokaal FBASCATI,
ten overslaan van de Notarissen W.
KRANEiNBURG en H. MOLESPAGF,
in veiling brengen, worden opmerk

zaam gemaakt, dut ook de beide be

lendende Koopmanshui/en »an den
N. /. Voorburgwal 151 en 153 UIT
DE HAND TE KOOP ZIJN. Met de
i» veiling aangeslagen Perceelen heeft
dit complex eene oppervlakte lan
183 M*, en eene gevelbreedte aan
de Pulei'Straat en N. Z. Voorburgwal
van circa *27' 'M. saam.
Nadere inlichtingen en iir-age der
Kadastrale Kaart etc. zijn te bekomen
ten kantore van den Makelaar H.
CROUWEL Jr., Weteringschans 71
te Amsterdam.
Algemeene Maatscbappij van Levensverzekering en Lijfrente
O gevestigd te AMSTERDAM, Damrak 74.
Goedgekeurd bij Koninklijk Besluit van l November 1880, No. 28.
DIRECTEUBEN:
Dr. S. R. J. v. SCBEVICHAVEiV, E. \V. SCOTT en J. F. L. BLASKEMERG.

C Secretaris der Directie: fflr. J. . SCUEÏICUAIEH.
Volteekend Maatschappelijk Kapitaal f 1.000.000.
Verzekerd Kapitaal .•125.151.458.2:1
Verzekerde Rente 246*681.41
Ontvangsten in 1903 8.968.489.815
Reserven op 31 December 1908 84.180.722.76
Tot 31 December 1903 aan verzekerden betaald	20.87-2.544.74J
Ouderdom.
25
3O
as
40
45
5O
JAAKLIJKSCHK premie yoor ƒ 1000.
bij orerlljden
aft U keeren.
ƒ 18
20
23
28
34
t
30
80
20
40
60
na 20 jaren | n» 15 jaren
of dadelijk bij overlijden
uit te keeren.
ƒ 41
41
42
43
46
51
10
60
40
90
70
ƒ 57
57
58
59
61
64
30
30
10
20
40
80
Ouderdom.
45
6O
65
6O
65
70
Dadelijk Ingaande i
Jaarlijksclie lijfrente roor
/ 100 gmtori kapitaal.
roor mannen. | roor Trouwen.
/ 76
8
9
11
13
83
54
39
57
18
51
' 7
" 7
: 9
10
13
65
24
99
10
72
03
Vermelding van enkele onderscheidingen den *'
Senior van het huis ERNST KAPS verleend.
C! V»
or.,
Ridder in de orde van den
Neder&amp;,»(***«» Le
Ridder Ie Klas Koninklijk Saksische
., AlbrecMs-orde.

Eere-P resident der Nationale Academie
te Parijs,
TTÏVtl Q+"
JUI11SU
CJv» Jurylid bij de Tentoonstelliiiqen te
I.t Amsterdam, Chemnitz, busseldorf.
EK*ST K APS Piano's en Vleugels,
Steeds in groote sorteering voorhanden bjj

G. A. GOLDSCHMEDING,
Warmoesstraat 141 en Keizersgracht 805, Amsterdam.
Catalogus gratis.'
Ruil van gebruikte Piano's van elk fabrikaat.
Sluit uw
Levensverzekering^
bij de
3OO Francs par niois tout Ie
monde peu les gagner en vendant
charmantes nouveaute artistique.
Hcrire: Pennellype?. C.o Milan
(Italië!.
Bij A. H. ADRIANI te Leiden ver

schijnt :
VO\ HOK\*BROFX H

HET PAUSDOM
i ii zijne werkzaamheid
op maatschap/lelijk m t/eextelijk f/*'bi«l.
Kerste aflevering. Prijs: 60 cent.
(Compleet in 4 afleveringen : ƒ 2.40.)
, Amsterdamsche
Keizersgracht 547=549,
MAATSCHAPPEUJK KAPITAAL F.I.ODQOÜD
De Zi
Maatschap?
en U Mie,
te 's-flravenhage,
HÉERENGRACHT 12.
Goedgekeurd bij Koninklijke besluiten.

Maatschappelijk Kapitaal:

léa Millloen &amp;ulde&amp;&gt;

Commissarisgen: Mr. M. M. SCIII&amp;
VAN DER LOEFF (President); W. B
VAN LIEFLAND; Dr. A. E. TEK
OEVER; A. M. VAN EMBDEN; Di
P. H. J. BERENDS; Mr. J. W. DE
KANTER; Mr. A. S. MIEDEMA (Secretaris}.
Directeur: Mr. J. W. KONING.
Wiskundig Adviseur: Dr. A. v. ELDIK
Genees*. Adv.: Dr. C. M. DE JONG
De Maatschappij slnit alle soorten Levens-,Werkkracht- en Ziekteverzekeringen
In de verschenen afl. van den jaargang 1905 van het
Populair Geïllustreerd Maandschrift

-:- DE NATUUE,
-:komen o. a. de volgende opstellen voor:
De oorsprong cïer Mnanbergeji. Weervoorspelling. Antbropologische Af

stamming. De ontwikkeling der Luchtvaart in 1904. Ov&lt;r de kuituur van
vijgen. Nesten van weide- en moerasvogels. De teelt en tentoonstelling der
variëteiten van de huismuis. De verandering in het bedrijf der gemeente

tram van Amsterdam. Nieuwere toepassingen van den spiritus in de industrie
en do huishouding. Het meten bij den electrischen stroom. Het kweeken van
goudvisschen. Kathodestralen. Omzetting van wisselstroom in gelijkstroom eni.
Prijs per jaargang .... /5.2O.
Proefafl. zijn gratis verkrijgbaar bij de Uitgever J. G. BROESE,
te Utrecht.
•^•^•^•^•^•^•^•^•^•^•^•^•^•^•^•^•^•^•^•^•^•^•^•^•^•^•^•^•^•^•^•^•^•^•^•^•^•^•^•^•^•^•^••••••••i

Eerste Rotterdamsche
Maatschappij van "Verzekering op het I. e v e n tegen
Ongelukken en Invaliditeit.
Sluit Verzekeringen op het lieven in verschillende vormen,
Lijfrenten, Pensioenen enz.


Eerste Rotterdamsche
Maatschappij van Verzekering tegen Ongevallen.
Verzekert tegen Ongevallen over de geheele wereld. Neemt
het risico van werkgevers over volgens de Ongevallenwet.
Beide Maatschappijen zijn gevestigd:
i\o. l, i*lan C.
p. R. MEI:?.
Directeuren:
J. F. WEKTERBERG.
Weet gij WA! Electriciteit is 1

Weet gij WAAR Electriciteit is?
Deze beide vragen worden beantwoord in
De Hoofdbegrippen over Electriciteit",
door A. TKJf BOSCH Sf.Jz., Electro-Inycnüur, Prijs ƒ0,75.
De uitgever .E. E. KLUVVER, te Deventer, zendt het franco na ontvangst
van postwissel.
Tweede
gevestigd te HAARLEM. Opgericht 1870.
D p muil lak klirilKl'ill Prachtig gelegen bij het Kurhaus en
l. llieU. LUIS nUldlISldU. het Bosch. Geïllustreerde prospectus.
Voor zenuwljjders en als uitspanningsoord. PM'«.i«j
Speciale behandeling bjj hoofdpijn, congestie,
neuragenie. in Thür.
Drinkt S C h l O S
Snatuurlijk tafelwater lste klasse.
Algemeeiie Maatschappij van Verzekering op het
leven en bij Ziekte.
i
. Gevestigd te Tiel.
Goedgekeurd btf Koninklijk Besluit van 7 Februari 1902, No. X3.

Maatschappelijk Kapitaal: ƒ1,000,000.
Directeuren: A. GROENEN D AAL C. Jzn. en Mr. C. R. A. EYS VOGEL.
Alom tr orden ehwame Agenten gevraagd.

KINADRUPPELS van Dr, DE VRIJ,
Het krachtigst werkend middel tegen
Malaria (binnenkoortsen) algemeene
zwakte, bloedarmoede en bleekzucht.
Prijs per flacon / 1. . Men eische steeds
mijn naam buiten op de roode doos, daar
goedkoope namanksels in omloop zijn.
Bij overmaking van een postwissel a
/ 1.15 volgt franco toezending door de
C li e m i s c li e 1^ n l^ i- i e lc
NEDERLANDSCHE BANKINSTELLING flttentie.
?oor waarden belast met vruchtgebruik en periodieke
uitkeeringen, gevestigd te 's-Gravenhtige.
verstrekt gelden ter leen op Grootboekkapitalen, Onroerende
Go*eren, Hypothecaire Vorderingen, Nalatenschappen, Fondsen enz., belast mei
Vruchtgebruik of periodieke uitkeeringen.
De Bank koopt ook dergelijke waarden aan.
Nadere inlichtingen worden gaarne verstrekt door de DIRECTIE, EorU
Tcorhout 18, te 's-Gravenhage.
Wij zijn begonnen in onze verpakte artikelen fotoplnatjt's te verpak

ten, die in ons Albnm, overal verkrijgbaar 4 25 cent, alsmede aan onz«
kbriek en waarin 144 foto's bestaande in 24 Serie», geplaatst kunnen
worden en een schoon geheel vormen. Vraag ons Album en onze
Oiitkijtkoek in carton &amp; 3O cent en in vetvrijpa;&gt;ier &amp;. 25 cent, en onz«
indere verpakte artikelen, die door het laatste onderzoek van deskundigen
bewezen de beste te zijn. De dubbele foto's ruilen wij.
B. J. LINDEBOOM &amp; ZONEN, Amsterdam. Koekfabriek De Nederlander".
Wereldberoemde badplaats in het Sellwarzvvald, gezond en heerlijk gelegen, door de dichtbegroeide bergen
tegen ruwe winden beschut. Door de Ju'e.te, bronnen" van 45—(il) K C. en de prachtige
badgelegenheden in elk opzicht en op de hoogte van zijn tijd zijnde badplaats van den eenten rawj. Alle moderne
geneesk. inrichtingen. In den lierfxt rit' ilruirrnkuur. Prospectus verzendt das Stadt. Kur-Comité.
van H. NANNING, DEN HAAG.
V1ÏZNA
Ftigi-Spoorweg.

Hotel Yit/.iiaiier Hof' Pension,

comfortabel hotel, eerste rang, te midden vnn prachtige en
schaduwrijke parken en tuinen aan het
meer.Veranda's.Centraalverwarming:, eleetrisch licht, 100 liedden, lift, badinricut'mg
in het meer, baden en douches, motor- en roeibooten.
Pensionsprijs met inbegrip van een kamer vanaf 8 francs.
Eigenaar:
F. MICHEL-AMBERGER &amp; Cie.
NATIONALE
LEVENSVERZEKERING-BANK.
Boompjes n*. 9 eu f», R O TT K R D AM. Opgericht 17 Januari 1863.
Benige maatschappij, die aan verzekerden pandrecht
verleent op de beleggingen in effecten.
Vertegenwoordiger op de Beurs te Amsterdam: J. W. MEIJJES Jr., Hoofd van het
Bijkantoor, DAM 4.
Inspecteur voor Xoorrt- en /iiid-HoIland: I. I. K L U Y S K E &gt;'S te VOravenhasre, Groothertoginnelaan 133.
//irccfeitrcn: J. W. NIEMELJER; K. C. SOMMEE.
AM5TE.RDAM.
Biljardballen
Ie qualitelt lyoor met garantie, alsmede Laken»,
Queuen, Pommeranzen en verdere Biljard-ArtL
kelen. En-gros bij A. OVERES, 't-Hertoaenbotc\.
Koopt owle ballen legen hoogen priji.
/^BfP " T&gt;\
/j^x' ^ ^V
V^&amp;t-ji»**- " "^X\
Helm"-Cacao en Chocolade
ZIJN ZUIVER, SMAKELIJK EN GEZOND.
Probeer vooral Chocolade Kacquis.
Nederlandsche Cacaofabriek, Helmond.
PORTORICO
BB 12C per pakje
Zijn niet te overrreFFén
Voor Fijnere soorten zie
de prijscourant in elk pakje
Typ. Ainsterd.
Bojkv;'h. Ellenuan,
en Stecmli'ukkerij,
Harnis &amp; ('o.

</text>
<image timestamp="2002:08:21:14:05:34.00" size="372289">D2002BC.TIF</image>
</page>
</document>
