<?xml version="1.0" encoding="windows-1252" standalone="yes"?>
<!DOCTYPE document [
  <!ELEMENT document   (languageid,page*)>
  <!ELEMENT languageid (#PCDATA)>
  <!ELEMENT page       (pagenumber,text?,image?)>
  <!ELEMENT pagenumber (#PCDATA)>
  <!ELEMENT text       (#PCDATA)>
  <!ELEMENT image      (#PCDATA)>
  <!ATTLIST image      timestamp CDATA #REQUIRED
                       size      CDATA #REQUIRED>
]>
<document>
<languageid>21</languageid>
<page>
<pagenumber>1</pagenumber>
<text>
Muziek
VOOR HET
KERSTFEEST
PAPIERWAREN 2e ETAGE
KERSTTAFELLOPER
met Servetten
KERSTSERVETTEN reeds
gevouwen, voor de stan- /\ .f c
daards	U.l D
HULSTTAKJES /% /%«
groen 0.04 U.UZ
HULSTTAKJES
zilver	0.05
ZILVEREN KERST- n
/MKRANSJES 0.10 U.UD
KERSTSLINGERS
O.25 0.20
IN WIKKELPAPIER MET KERST

MOTIEVEN per pakje
van "i 2 vel
DENNISON'S ARTIKELEN
KERSTKLEDEN	.. 0.60
KERSTLOPERS	0.45
SERVETTEN	0.20
KERSTLABELS	0.25
PISTACHES in dozen van 6 en
12 stuxs 1.50 1.35/t oc
1.1O 0.95	U.ÖD
TAARTRANDEN MET KERST.
MOTIEVEN per pak,e /% A e
vanaf........	O.45
SPcELGOEDAFD. 2e ETAGE
UITGEBREIDE: SORTERING
KERSTBOOMARTIKELEN
VOOR HET KERSTDINER
brengen wij in onze afdeling tafel*
goed een zeer groot assortiment
ZEER FRAAIE TAFELLAKENS
VOOR ZEER LAGE PRIJZEN
Solisten in het Concertgebouw
CONSTANT VAN WESSEM
O l' «lu laatste abonnement
sconcerten van het
l'oncertgebouw, onder leiding van
Mengelberg, die ik hier samenvatten&lt;l
bespreek, was het wel do opvullende
Russische opeia-/angeres Olga
Slobod s ka ja, die /.icli in het middelpunt
van onze indrukken geplaatst heeft
niet haar voordracht van Russische
liederen, aria's van Moussorgsky en
diens bekende bekoorlijke Ilorak.
De stem is sterk dramatisch van aan

leg, heeft een grooten omvang en wordt
met meesterschap bt-hecrscht. Van
het sterk dramatische overtuigde
vooral haar voordracht van
Beethoven's Ah J Perfido!", dat magis

traal en indrukwekkend gezongen
werd.
Op datzelfde concert herdacht men
den Nederlandschen componist Von
Bruckcn Fock naar aanleiding van
diens Tosten verjaardag met de uit

voering van zijn nieuwste werk, een
suite-muziek Uit het /uiden". Von
Urucken Fock was altijd een wat uit

zonderlijke figuur oiid'„&gt;r de Hollands -h
componisten van de vorige genernti1?;
van aanleg autodidact ging hij ook
veelal zijn eigen \veg.-hojwcl hij nL-t
ontkwam aan de romantische vUic van
xijn tijdgenooten. Poch naast de schier
conventioneel s.chijrende muzikale ro

mantiek van zijn expressits school
e&lt;in somber geweld, dit- dan opeens
do fantasie bevleugi-Ide en in zijn
muziek tot een meeslepende uitbar

sting werd en er dan iets
merkwaardig-eigens gaf. In dit laatste werk
van Von Htueken Fock is echter alleen
de lomantische aanleg overgebleven,
het is een liefelijke, soms Fransch
aandoende muziek, korte schetsen,
indrukken van Zuidelijke landschap.
en menschen, fantasiebeelden van
boschgecstcn cri van een ,.schalksch
meisje", wier gazellb-achtige bewege

lijkheid aardig, hoewel wat plastisch
van ihythrnc is weggegeven. In ieder
geval geen werk, dat een bijzondcren
indruk achter laat.

liet laatste abonnementsconcert
bracht Mahler's 4de Symphonic, een
der geliefdste stukken muziek zoowel
van Mengelberg als van het publiek,
een nooit missende charme komt er
uit tot ons, reeds de aanvang, d:e
klinkt als werd er met altaar-schellen
geluid, bekoort en wij glijden tot de
laatste noot van het Hemelfeest"
in den droom van geluid en fantasie,
een der weinige symphonische werken
van Mahler, waarin hem een volmaakt e
eenheid tusschen bedoeling en
verwei kelijking gelukte. Jo Vincent was
de soliste in het laatste deel. Wij
hebben in onze herinneiing voordracht
ten, waarbij de naïeve gelukzalige
toon idealer getroffen werd. wat niet
wegneemt, dat Jo Vincent haar pat-tij
pi acht ig zonti.
Journalistieke prentkunst
Jo Spier: Per potlood door
Nederland. 200teekeningen.
Andries Blitz, Amsterdam
WAT gewoonlijk voor den
luisteraar een veroordeling.
betekent is voor .loSpier's
w'erk juist een compliment: ITt-t bleef
door vele jaren heen .vrijwel op de

zelfde hoogte. In Spier's verbintenis
.met de Telegraaf ontdekte hij zijn
roeping na -vijf jaren dienst ge

tuigde hij juichend:
,.lk vind het nog even prettig als
d*- eerste dag !"
l'it deze nieuwe bundel blijkt, dat
die uitlating ook nu nog van kracht is.
Stuk voor stuk logenstraffen zijn
prenten de vele sombere voorspel

lingen, dat hij dooi"zijn verbond,
metde krant zijn kunstenaarschap en zijn
i«lcalismc ten dode doemde.
lL'et zuiverste bewijs hiervan vinden
wij in die prenten, waarvoor niet een
actuele gebeurtenis hem de stof lever

de, maar die ontstonden in zijn onge

breidelde fantasie. Heeds de mogelijk

heid dat zij konden ontstaan duidt er
op. dat zijn frisse geest niet leed ónder
de ,.dwang" van het maken
dieiandere.
Ken uiterst-links part ij-orgaan heeft
geconstateerd, dat Spier zijn bete

kenis als tekenaar ontleende aan de
.. . .burgerlijke journalistiek, en dat
hij daarom als zodanig tot on vrucht»
b.uirheid is veroordeeld, ten/.ij.. .. hij
partij kiest in de politieke strijd'!
l-.aat ons verheugd zijn. dat hij dit
laatste n'n't d&lt;''fl—'zijn oorspronkelijke
zin voor humor is te gezond om
verhitter! te worden door het gekon

kel van part ijen-belang/.ucht.
Overigens is «Ie bedoelde opmerking
de 'ongewilde weerlegging van een
verwijt, dat een zeer bekend
kunstrritikus tot .Jo Spier richtte, n.l. dat
hij geen fors of-psychologisch talent
zou bezitten.
Iemand heeft Spier's merkwaardige
zin voor humor onlangs gekenschetst
als Anglikaans. Kn dit is inderdaad
goed gezien. Met de Engelsen deelt
hij de gave. dingen van dagelijkse
sleur om te zetten in davei;endc
zotheden. Ken aanzien van 's mensen
eigenaardigheden krijgt zijn werk
daardoor op voldoende kracht. Kn
evenmin als bij de Kngelse
caricatur i sten word. t zijn spot ooit wrang of
kwetsend. Wij zien onze eigen
welbewuste- 'fouten' in een heldere
spiegel en we lachen, zij het
wellicht ook eer ironisch dan uit

bundig. .
Ken krant lezen Ls in onze dagen
amper een amusement. Laat ons
daarom erkentelijk zijn dat Jo Spier's
gezonde, dwaze kunst ons eraan blijft
herinneren, dat dit leven ook nog een
zonzijde heeft !
WYBO MKYKU
CABARET EN DANCING
LEIDSCHËPLEIN
Icdprcn avond 8'/t uur Soiree-Dansante
met optreden van
I X T E II \ A T I O X A L E A II T I 8 T E N
Vrij entree Dansen tot Zondag matinee
Verlaag tarief • 12.45 uur - 3.30—6 uur
HET PALEIS DER LIEFDE
Albert Heiman
Teekeningen W. v. d. Elzen
RKKDS op zijn twintigste jaar
was Urn Taehfin khalifa* van
liet Westen. Het was niet enkel
op grond van zijn edele geboorte, dat
hij zoo jong al tot zulk een gewichtig
ambt verkozen werd. Nog meer dan
zijn koninklijke afkomst, die duidelijk
te zien was aan de fijne regelmatige
trekken van zijii blank gezicht, de
gi-oote smalle adelaarsneus, die zich
tot bijna over de bovenlip heenboog,
«Ie scherpgeteekende ernstige mond.
de hooge gestalte die nog eens zoo
groot en verheven scheen in het
smettelooze wit van zijn wijde kaftan.
de lange blanke handen waarmee hij
in sobere gebaren kracht bijzette aan
zijn woorden, meer n,og &lt;k"1 u' deze
uiterlijke schoonheid onderscheidde
hem de adeldom van zijn geest. «Ie
helderheid van. zijn verstand, gepaard
aan zulk een rijkdom en zuiverheid
vangevoelens.dat daardoor een geheel
ontstond van zeldzame harmonie en
Universaliteit: zoodat iedereen ge

troffen werd door zooveel volmaakt

heid in n metisch. en zijn jeugdige
leeftijd enkel gold om. dit
allerkostbaarst be/.it nog meer glans bij te
zetten.
J lij aanvaardde zijn khalifaat vol
grootsche voornemens, rustig maar
zelfbesloten. en'hij koesterde de over

tuiging dat iets waardevols voor
anderen slechts tot stand te brengen
is wanneer wij zelf van dag tot dag
ons rekenschap geven van de. recht e
weg. aan ons zelf bouwen en ons in de
eigen ziel verdiepen, opdat wij niet
door droombeelden eit
valsehe voorspiegelingen het
spoor bijster raken in een
wereld waarin bedriegelijke
schijn en werkelijkheid
soms ternauwernood
van elkander t e
onder «c J.eiYeii
zijn. IbnTachfin
w a s e r v a n
docrdiongetv
dat een volk regeeren in de eerste
plaats bet eekent: zichzelf regeeren;
een volk gelukkig maken niet mogelijk
is voordat men zelf geluk van ongeluk
heeft leereii onderscheiden. Hij wist
dat «en vorst de verpersoonlijking van
het ideaal van zijn volk moest zijn, en
daarom liet hij niets na wat ertoe kon
bijdragen zijn aanzien bij de onder

danen te vergrooten en hem zelf beter,
edelmoediger, schooner in hun oogen
te doen schijnen. Hij dee«l dit niet
uit ijdelheid, maar om inderdaad
zichzelf te vermooien. zijn ziel te
verrijken, zijn omgeving schitterender
te doen zijn. in een zelfzucht die ten

slotte toch een heerlijke deugd was.
omdat ze haar diepst e-grond had in de
liefde voor zijn volk en uiteimlelijk
weer terugging tot dat volk.
Teneinde beter zichzelf te kunnen
zijn. de rijke, edele vorst, «lic hij zich
voorgenomen 'had steeds te zullen
we/en, had hij zich een paleis
laten bouwen van ren omvang
en e-en Weelde zooals het rijk
Uog niet gekend had. Dr hoofd

gebouwen met hun groen
gegla/.iiurde daken en «h;
talrijke paviljoens .^
met hun witte koe

pels waren
omg e v e n door
groot e
palin e
nb oo rn ga a r de n,
waartusschen do
schoonste bloem

perken, klaterende
fonteinen,
vischrijke bassins en
geheimzinnige ;
priëelen waren
a a n g-e legd.
lui zo &lt;j dra,
deze tuin ge

reed was en
van du
bui
temvereldafgeslotetidoof
een hooge
aard e n
muur.
verlieDe arme vrouwen, die zijn ideaal niet vermochten
te -naderen
ten de vogels
van heel de om

trek hun 'vroe

gere
verblijfplaatsenen
bouwden voort

aan in de booineii van
dit paradijs hun nes

ten, zoodat er een
vt«-rt durend
gekwinkeleer was van. hooge
muziek die zich vermengde
met het geklater der water

werken. Alleamrer-, muskus
en blot-meh-gevu'en ter wereld
schenen zich verzameld te
hebben om de vijvers waarin
goudvisschen dartelden. Ken enkele die

naar slechts, gekleid in roode zijde,
het -hoofd in een groot e witte tul

band gehuld, zag men er gei-uischloos
voorbijgaan. Pe galerijen, die som

mige der paviljoens met het paleis
verbonden, waren begroeid' met win

gerdranken en eeuwig-bloeiende
glyci net rossen, omzot-tml door bijen
en schitterend in het zonlicht,- In d«!
zalen en kamers van het paleis was
koele si-hemerdonkerte en al het wel

behagen van een Meinacht.
Vele uren bracht Ibn Taehfin in
«leze omgeving door. alleen en in
ge«lachtch verzonken, rustig en gelukkig.
zinnend op de groot o werken diéhij
volbrengen moest- tot vooideel van zijn.
volk. J l ij had geen 'raadslieden nootlig
en verlangde niet naar de ijdele
«liukte van een hofhouding om, zich
heen,.noch naar het vleicrig gekir van
vrouwen die wel de \u-en vcrpet«n
«loe'n. maar tot geen enkele daad, vj!»
bezinning weten aan .terzetten. 1«
PAG. 18 WINTERNUMMER No. 3003
PAG. 19 WINTERNUMMER NO. 3003

</text>
<image timestamp="2002:11:06:21:42:51.00" size="508259">D3000JB8.TIF</image>
</page>
</document>
