<?xml version="1.0" encoding="windows-1252" standalone="yes"?>
<!DOCTYPE document [
  <!ELEMENT document   (languageid,page*)>
  <!ELEMENT languageid (#PCDATA)>
  <!ELEMENT page       (pagenumber,text?,image?)>
  <!ELEMENT pagenumber (#PCDATA)>
  <!ELEMENT text       (#PCDATA)>
  <!ELEMENT image      (#PCDATA)>
  <!ATTLIST image      timestamp CDATA #REQUIRED
                       size      CDATA #REQUIRED>
]>
<document>
<languageid>21</languageid>
<page>
<pagenumber>1</pagenumber>
<text>
Dirk Sontvoort (1610—1680)
Portret van Agatha Gee/vmck
|!
Nederlandse vrouwengezichten
op wit en gekleurd doek
EEN g.uiden eeuw van schil

derkunst lu-cft liet Nederlandse
•vrouwongozicht over do wereld
godrajiV-n. Daar hangen zij nu. de
Amsterdamse Saskia's. do Vlaamse
Helene Fourmont's on Isabella
Brant's on de rijke burgercssen van
Piotc-r'do Hoogh en Vermeer in do
plechtige inuseumzalen van Europa
en Amerika, haaf statig' figuren in
de woelde van warm fluweel on glan

zend satijn, van glinsterend brokaat.
ijle kant en parelen sieraden g.wat
in vergalde lijsten, en b:»vcn de rijk

dom haivr kleuing en tegen do don

kerte van haar avhtoffifoml staan
haar witte gezichten als brede
lichtkegels. Het zijn gezichten die voor
óns levend zijn ondanks de uiterlijke
maskerade van oen vo«)rbijgogane
periode, die ons dagelijks op straat
of in eafó's aankijken bovendo om

hulling van oen toogeslag.-n
b;mtkraag of omlijst do«jr d.e grillige
lijnon van een moderne
hoofdbedekking. Want het Nederlandse
vrouwong„'zicht is niet \vraixdord in al die
tijd: het is hetzelfde ietwat hard
lichtvlak gebleven, dezelfde bleke
wangen vervloeien langs bolle konen
tot een vaag profiel, de glanzende
ogen liggen v.'xJr in hun kassen, het
is een nuchter en onromantisch ge

zicht, een strak gezicht zonder illusie
en dus zónder teleurstellingen, maar
een gezicht dat zeke.r niet ontbloot,
is van charme en. dat alleen de warmte
van kostbare stoffen en de schittering
van sieraden behoeft om in zijn
onverstoorbare rust geheel tot zijn
recht te komen. Het zijn deze attri

buten van rijkdom die de
midischilders met zooveel , zorg rang

schikten om hun modellen totdat
er zo'n glans on gloed was rondom
dit witte c n moeilijke "gezicht dat
het l«vk alsof het matte kci.s'tal van
een ijsbloom opbloeide togon de
donkcro val van «'en fluwelen gordijn.'
Onze tijd. wiavin fotografie en
film een populariteit hebben gekregen
«lic z &gt;lfs «'"o schilderkunst van de eeuw
van hot p.-n.se'.'l b'j vem&gt; niet kon
b .«naderen, g.-b.-tiikt «leze moderne
technische middelen om haar leven
te reproduceren: van de p ilitioko en
.tociale geschiedenis van onze dagen.
vin on/.:- kuituur en ons mensentype
zullen in later tijd*«n filmen fotografie
een volledig archief vormen, ..«Ie
moderne vrouw" zal als een gVa'Mourfe
schim uit lang vervlogen dagon in
stille melancholie over het witte doek
gaan ««n m«m zal haar stem de dingen
horen zegg-n die ons- 'nu vertrouwd
zijn. En ook de Ncdorlaixdse vrouw
zal in d.e b'.ikken bussen «lor
film' rollen . voor liet nagoslaeht
gekonsor\verd • worden. Maar als er nu rc-etls
een oordeel over uit te spreken is
hoe Onze jongste .nationale, industrie
hot Nederlandse vrouwengezicht
pr&lt;»jectoert dan moeten wij zoggen (als
wij tenminste heel eerlijk willen zijn):
..Noen, zo flatteus als do schilders
doen zij het toch niet!" En onze
ijdelheid dio zo bijzonder gauw in
opstand komt verweert zich een beetje
togen de vergelijking van do Neder

landse film vrouw mot do Amerikaanse.
toonbeeld van schoonheid on karakter.
Ligt hot er aan dat hot gelukkige
Ifollywood de boste
schoonhoidsexperts van do wereld rijk is. die uit
het slordig,-, onopvallende Berlijnse
filmspeolstortjo C rota (ïarbo do stra

lende ster van hot filmfirmamont
konden maken? Schoonhoidsexperts,
waarmoe goen enkele filmindustrie
on zeker niet do beginnende Neder

landse kan k«mkurreren? Ik geloof
oerder dat het technisch procéd
van fotografie en film zich niet in
dezelfde mate als do schilderkunst
loont tot hot naar voren bi-engen van
do ..b;&gt;st points" van het Nederlandse
\Y«»uwengo7.icht. Zolang do kleuren

film niet oen bruikbare volmaaktheid
hoeft bereikt mist immers de film
hot element van do kleur dio do
schil«lers op zo geraffineerde wijze ge

bruikten als in hot oog vallend kon

trast mot de stille, witte gezichten;
on zolang do film nog de derde dimen

sie van do diepte mist ontbreekt eo
ipso hot juiste porspoktief voor hot
enigszins platte vlak van hot Neder

landse vi'oimvngelaat. Hot is daarom
«lat het geestige k«&gt;pjo van een
toneelspeolster on ehansmmière als Piontje
de la Mar ..hot minder good doet"
op de film dan men zou verwachten,
dat het fijne bleke snoetje van oen
Itelga (&gt;ogh'iuuior de
Volondammormuts van Dood Water" te gi'ijs on
strak blijft om zijn volle aantrekke

lijkheid te b.'houdon. dat .0011 Jopie
Koopman, proto-typo van de
..Hollan d se Ho v,- meid", g.'of Ivgint te
lijken on dat talloze
figuranteiige/.iehtjos vervelen l aandoen.
Kleur en diepte zijn nu eenmaal
fa-toren die ons vrouwenge/icht
ii'nlig S'-hijnt te hebban om niet
flets en levenloos te lijken, en hot is
JH'innor «lat de film haai' «loze om

lijsting nog niet kan geven. Daarom
zie ik on'.' No lo;'la'i Is" filnui'-'trice.s
(waar.ui'ler «-r tot nu toe trouwens
slechts n.' Knny .MVunier. in «Ie
w.ive zin dos w.»or,ls fotogoniek
geniifiud kan worden) nog altijd liever
op hot toneel of t&gt;p straat dan op
hot witte doek. dat haar wol in volta
wa'ir&amp;'.'htigJioM kan weergeven maar
waarop zij nooit haar ..beau jour''
/uilen kunnen beleven, omdat de
technische geaardheid van de tegen

woordige film hot naar voren brengen
van haar moest flatteus*- trekjes
niét toelaat.

'ELLEN KAIIN
INTERNATIONALE
J. Riemens
Truus van Aalten als Het Meisje met de
Blauwe Hoed" in de gelijknamige film
Een oud slot met jong leven
HET statige,
achttionde-eeuwscho kasteel Eer.le te Ommen
is feestelijk van onder tot b;&gt;veii
verlicht, om de gaston, dio tjt voet.
per bus of auto van heinde on verre.
komen, plechtig te ontvangen.
Maar als gij bij hot binnenkomen
onder den indruk geraakt van do
hoogt' ruimten, van de zware tapijten.
Van de kleurige gobelins on het
donker eikenhout uit de vorige eeuwen.
dan komen daar lieve eenvoudige
kinderen van onzon tijd. om xi rustig,
natuurlijk on vriendelijk behulpzaam
te zijn met hot afnemen van uw kloedij,
met b j-.Henen van thee en
eigengobikken heerlijkheden, met hot toonen
van school en werk.
'A &gt;o zuiver on eenvoudig kan alleen
«on kind zijn. dat aardt in oen
levonsb:&gt;dem.
En als deze twee indrukken
eenigszins \vnverkt zijn: het statige van do
aula-kasteelhal on do bevallige vrien

delijkheid dor kinderen, dan merkt gij
op. hoe daar zoo'vole b.ïssoekers
gekoni"M zijn van ver. maar ook van hooi
«lichtbij: hoe «kr voel inw.moivi zijn
vaix Ommen, kunstenaars, onderwijs-,
menschea. belangstellenden.
Daaruit concludeert gij dan direct
»'en bepaalde bedoeling van de
dire«:trico dor school: Fra'.i iVof.-ssor
'etorson «'n haar staf: om een govaar te
ontl«K&gt;p."v. d»it s;&gt;nrnigo L m
lor/iehungshoime aankleeft, n.l. leerlingen
téayart op t-&lt;&gt; voeden, téveel buiten
hot gew.mo loveïi. (iij verbaast n er
«•ver. hoe do/.e b.- loeling reeds na «»on
half jaar werken zich in alles
demonstroert.
En go zoekt naar de bedoeling. «Ion
achtergrond van deze school.

Hoe de school ontstond
SIND3 «Ie oprichting van «Ie
Quaker'.genu'onschapin'den bewogontijd. van
Hendrik VIII. hobbv»n do v,&gt;lgolingen
van John Fox zijn idealen zuiver we

ten te bewareiveii ze op praktische wijze. .
trachten te Verwezenlijken:
onkroukbaarhoid. «-n good.-will jegens- ieder.
Door d«? eerste eigenschap verwier

ven zij. vooral bij de opkomst van het
kapitalisme, oen groot vertrouwen:
velen bekleedden hooge.posten: «laar
hun winsten ni«-t ten «;ig«-n nutte, maar
ton algomeonon bate gebruikt moeten
worden, werd do gemeenschap rijk.
Tiia'is i« te Li»n«l«'n oen enorm '
centrum ge vestig» l, «lat een . w
jdvertakten«li«'nst• omïorhoüdt «»ver «!e g«"
heolo wereld: vooral internationaio
samenwerking is het streven.
l{e«'ds goruimen tijd bestond, het
plan. een internationale scho«tl te,
stichten: d&lt;- gebeurtenissen van d
laatste jaivn liebbeti' «lat plan «loon
verwezenlijken., on als standplaats
word go kozen Nederlan«l. waar men
zocht naar «-en plaats dicht bij «Ie
Duitscho grons. Want vooral zou do
sch«j«tl zijn voor half- of driekwart'
Arische kind«rron. dio een nk-uw va

derland moeten zo&lt;'koü. of voor
kimloivn. waarvoor om allerlei rede

nen een ander opvoódingsverband
g&lt;&gt;zocht .moest wórden.
Hierbij rekomlo men ook op
Hollanc'sohc en Engelschc pupillen om zoo

doende hot ideaal: internationale
s.tmenwerking.te kunnen verwezenlijken.
Zoo is dan in April d.e
Quakerschool geopend met zes leerlingen;
togen half December stuurde zij
uitnoodigingeix rond, om haar vrienden
de eerste resultaten harer arbeid te
toonen, een werk, dat zich thans
reeds over twee en veertig kinderen
uitstrekt.
Na deze oriëntatie staat uw geest
QUAKERSCHOOL Avontuur in Itali
Reurslag
PAG. 16 DE GROENE No. 3002
«»pen. om alles op te nomen wat u
gob«&gt;den wordt: do roerende
korstspelen der kleinen, do demonstratie
van oen Engelsche los.
Natuurlijk noemt hot omlerwijs in
hot Engolsch oen groot c plaats in:
wie verder willen studooron. zullen
klaargemaakt worden voor hot
Eixgolsche Staatsexamen, on, zijn er
eenmaal voldoende Hollandsche kin

deren, ook voor Hollandsche examens.
Er moest een methode gezocht
worden, die kindoren van geheel ver

schillende leeftijden konden volgen:
men workt zooveel mogelijk in
groepverband on cursusgowijs, niet indivi

duooi.
Voor de los in hot Engolsch waren
«lo acht- tot twaalfjarigen bijeen, do
inothodo was zeer direct; de kinderen
verrichtten do handelingen, die be

hoorden bij to weep - wept - wept. t«&gt;
break - broke - brokeh. Ook vertelden
/ij vrijmoedig van hun omgeving,
want alles is erop ingericht hun het
Kngolsch als «migangstaal bij
t«brengen, om later in oen groot er
vaderlan«l zich thuis to gevoelen.
Ook Hollündsch wonlt onderwezen.
:'i\ de praktijk wees uit hoe aardig zij
•r zich al in wisten te- redden.
De ochtenden zijn voor ernstige
«tudie, «Ie middagen' voor sport of
lmn«l«'narbci«l: of eigenlijk is
hamloiii'lK'hl een euphomist isch woor«l.
lichaam.-ijirbeid is beter.
Afbeeldingen «•!! nuuiuotto t»»«»ncn
lo. reeds huif voltooide, plannen van
•on zwomb.issin: en «lo/e graafarb«-id
s housch goen s.inocuro.
Dan wordt «lo tuin door leerlingen
•ndorhouden.de groente /.elf gekweekt.
Ie meisjes behartigen onder leid ing tle
huishouding en iedor h«&gt;lpt mot aard

appelschillen on groente st-hoonmaken.
Er is oon voet balelf tal. maar dat is
'.nn samongosteld dat er een paar
ongons uit Ommen in het
schooloam zitten, en omgekeerd; er w.ir.leii
iets- en wandeltochten ondernomen.
naar er wordt vooral gewerkt. '
'Heel m«&gt;«»i was het pottenbakkers-,
vork onder leiding van Thora Hofstede
'ruil. wier artistieke arbeUl bekend is.
Kr was b.v. con luchter van oen soort.
1 crra-cotta. van zeer grooto zuiverheid.
•'•n kom van oon haast
porseleintchtige fijnheid."oen-grappig b'oMjc.
f n do bijgebouwen, zijn'do
schoolokalon, hot internaat, en d«-
w»/rki'ilaatseh: do Wraven. waavvau enkelen
,'chuw.l. zijn intern, zoodoende w. ml t
'iet hier een groot o wo.rk- en
w.mngo'iieenschap, wat altijd «!«• i«lealo vorm
&gt; gowoest voor «-on kostschool.
Do kleintjes dor leeraren sluit«&gt;n als
!..ib;»uters «lo rij der lecrling-n jif:
••en grooj;. go/in lijkt h«'t. mot jongens
MI meisjes van Verschillende looft ijdeix.
Eenvoudig is «Ie maaltijd aan «lo
^ i t geschuurde ttifols. vroolijk zijn de
-••sprekken.- Afen ziet uiterlijkheden.
naar onder deze uiterlijkheden voelt
ucii hét Ie\vm\vkkond. practisch
ui't• lerbare ideaal 'dor Quakers,
(•emeen'••hapszin, eerbied v.u.ir 'elkaar, «son
'iiivere lovonshou:ling, dit' zijn d«;
ichtlijnon.
Maar het is al spoedig tijd. «»m luien
•••• gaan: oen jongen licluVóns eigener
''i'Weging mot zijn zaklantaarn bij in
Ie dónkctv laan.'
Buiten is het donker on stJinbjr;
'•• weten aan allo kanton de afbraak.
• ontmoediging, do teleurstelling.
Maar iets van het licht dat binnen
-lansde, nomen we mee: hier is
c«mstructio. hier is opbouw: hier zijn
«laden zonder woorden &lt;&gt;f zuchten.,
Nederland is in do international*»
Quakerschool oon belangrijk
opvoolingsinstituut rijk geworden.
WIJ zaten op het terras van
onze villa «&gt;p Lido. De laat

ste zonnestralen verlichtten
Venetiö's sprookjespaleizen aan den
overkant van de lagun«' m«'t oon
goud-roodon glans. Af en toe gloed
oon gondel voorbij, klonk de roep van
oon gondolioro.
Dus morgen gaan wij naar l'adua",
besloot Jan oon lange tirade togen
enkel maar zonnen, zwemmen en
luieren, waar niemand naar geluisterd
had. ..l'adua. (Jiotto," mompelde ik.
Maiitegna on Donatolh»," viel Jimmy
bij. ,.Sant' Antonio." zuchtte
C.'oncetta. 'unt n was hiermee afge

handeld, punt twee was: hoe?, 'êr
trein\ 'or auto over do nieuwe brug?
'Por, tram langs «lo Brenta, besloten
wij eenparig.
Di n volgenden morgen vroeg op
weg. natuurlijk mot stralend weer,
maar wie verwacht «&gt;«jk anders in
Italië? Op het bootje naar Veneti
raakte C'oncetta. mijn Napolitnansclu»
on dus bijg«'l«Kivigo vriendin, al
in verrukking, /ij had oen gobbo.
oen gebochelde. ont«l«'kt en wrong
zich in slinkscho bochten om don
bochel aan te raken. Dat bracht
immers geluk.... zou Attilio /ich
dan misschien toch nog declareercn!'
Een volgend bootje bracht ons
over oen geheel verlaten deel van de
lagune di«-ht onder het water
schemeren de mislukte eilanden, wion
het niet gegeven is boven water te
kouion on het g.'uldolijke \Vnetie
te dragen naar hot miemseopiseh
kleine Fusina. Mot «-enige hoeivn
stappen wij «laar in de'tram. oen
gó«nligo. ouderwetselie tram. waar
men eigenlijk oen paard voor /.uu
verwachten, ('.mcotta slaakt een
vreug lokivet. Op «lo achterste bank
zitten, angstig t«-geiv elkaar gedrukt.
twoe zielige twoeling/.iisjes . . . . . met
b irhols !
Als nie&gt;i Amsterdam lu-t N'eiielie
van hot Noor.loii no«'tnt. dan .mag
/oker «Ie Bivnta de \"ocht van het
X liden booten. Ken vlak landscha1.»
mot. ka uilen. «•:•» kalm v!ioden«le
rivier, aan «Ie oevers oen rij van statige
buitenplaats'n. waai- «lo
Venetiaanscho kooplieden zich kwamen
verl/oozeii. Z'ioals hun Amsterdamsclie
collega's a«n i!o Vecht. e.n vooral
ook een. sfeer va \ «l-t't igheid. In Itali
zijn veel liefelijke, indrukwekkende.
schilderachtige, ontroerend schoone
oordon, deftig is het alleen aan &lt;!&lt;•
Bronta. Z-'lfs do bouwstijl komt ons
bekend voor. Die breedo gttvels nu-t
zware pilasters, mot guirlandes on
frontons, wij kennen /e ook van
&lt;»nz&lt;oud-Hollandsche patriciërshuizen. Wij
zijn dan ook hier in hot gebied van
3'alladio, den Hldo-oouwschon
NoordItaliaanschon bouwmeester, dio in
Holland zo«/n invloed hooft gehad.
Alleen do afmetingen zijn «.mgekend
groot.
Bij do grootste buitenplaats, de
Villa Hoale te Stra. stappen wij uit.
Een in«lrukwokkeni?e faca«l.«'. oen reeks
van prachtige zalen. e«-n grandioze'
plafondschildering van Tiepol*» «-u
bovendien «ren schat van
ISde-eeuwscho meubelen (zoo zeldzaam in
Italië), sierlijk en toch s«»bor on
oenvoudig. zo«»als in een buitenhuis
betaamt. Dan '/werven wij &lt;l««»r hot
prachtig aangeh-gtlo jjark. Na iedere
kronkeling van liet pad weer nieuwe
verrassingen, ('oncetta wordt bleek
van ontroering: vó«'u- ons oen rij
van groteske tuiiilieeldjes. . . . alle'
met bochels \
l'as tegen donker k«nion wij aan
in l'adua. te laat . voor &lt;;ii&gt;tt&lt;&gt;.
Mantegnu ell Doliatelln., llo^' net op tijd
voor• Sant-Ant«tnio. Snel even
ori«-ijtooivn. dan naar ..II Sant*'", «'e LTI	te
Mi«l«l«'le«-uws« lio -kerk van d..-n II.
Antoiuus van'i'adua niet haar vi-t-, inde
Oostel'sche knepels. K\.-n eeli hlik
op Donatello's stoovo
i-uitej-standheeld ervó«'»r. dan met den stroom
nioo naar binnen. Donatello's prach

tige bronsroliëfs aan het hoofdaltaar.
Alticliiero's interessante
wan«'sehil«!eringen bewaar ik tot morgen. Nu
geniet ik enkel maar van «Ie sfeer.
het .kaarslicht enden wierookgeiir.
Ik /oek &lt;';»noetta en vind ln:ar in
«Irukke omlerhanil'eling niet e&lt; n oude
heks. die kaarsen . Verkoopt-: aan haai
voldaan ge/icht' zie' ik. «lat /ij m -t
succes heeft afgedongen. l'leclltiu
draaft /.ij haar gave naar het niet
wijgeschenkoii overladen altaar van
den heilige. Imniors-aan Sant' Antoni»
kan men ook kleine geaa-'en vragen.
laat staan «lo vervulling van hart
•uviisehen. Het terugvinden van
\viloivii v'. &gt;orworp«-n is eigenlijk y.ijji
specialiteit. .Al'beol«ling«'')i van al wat
Schepen varen voorbij ....
Xf varen voorbij. xooalH allén onze
«rmlnpnte J O SIMKR hen fllt kan
laten doen, li&lt;*t gt&gt;h«ele Jaar door.
in l'w f leen kamer, op de Mpeclaal
voor OHM In • O kleuren geteekrnde
luxc-kunHtkalender, zonder
rel&gt;oze O-liladltse kalender kost u
niets. In Kumcnwerklng met l'w
leverancier kunnen wij l'
haargratiH ter betüchlkklnK stellen, hij af

name van MlechtH n enkele fleneh
\VIJ.\ van Ol I&gt;. Bestel nog heden,
voorliet te laat IK. BIJ ieder familie

feestje ia WIJN van Ol I» op zijn
plaat*! .liet de komende feestdagen
zeker!
JO SPIKIl zorgde vooreen Juweeltje
aan den wand. wij voor een Mchat
op l'w tafel.
Wanneer het I' niet gemakkelijk K
WI.IN vuil «M I) te krijgen, se h rijft
l' ons a. u. h. even..
OUD
WI.IMiOOl'F.ll* - HAARLKM
ineji v, rui /.-u kan. \;tn kiin'.«-i---n tot
U;el«ilieUl&gt;jes. L-'tUiu'-il VJtll X.i.jn e.
iliipeteiitie. Ik raak onder den indruk. Mijn
horlo^..' /oek ik al \'.it&gt;n &lt;'a^,-n.
Lieve wij/.- Sant'' Antoiii... die
niedelijd.'ii hebt niet ons heehteïi aan de
kleille di}li.ell de- 1. \,-llS. 11. lp • lok Ulij .'
l-'n dj;n &gt;!eepeii de aiieeivii mij
UK •• naai- 'l'edroechi. &lt;!--it ie—tor, «ii-r
eal'e's. niet /ijn ItlaMWe. r»óde. LiiM.-n.'
ell Witte, /ijn Iv.\ ,itisèhe. dl-ieksehe
.•n i'omp"jai'Ms«-he /aal. llemaa'. « oht
Kmpir. : l'e Ir. «e. lii. al &gt;inus tn&gt; ei
di'ii e.-n . euw midd. Ipunt van i';i'iua'&gt;
lieaM-moiid'1 «n pi- -isterplaats van
nieiiiueji «v'-j-i-ltUrh n-i-neiii'«len pelgrim'.
Kn ten 'slotte hè, i't Attilio /j.-h
e'l.M'lareerd .n is mijn horloge tei'echt
yekomeii. uit «'e x.ak van mijn
reu-.-n'j;:s: de to.-ht wa-s Volmaakt g&lt; slaau'-i.
MC01.KTTK I U'sAKT
poduo: kerk van den H. Antonius
PAG. 17 DE GROENE No. 3302

</text>
<image timestamp="2002:11:06:21:36:11.00" size="584504">D3000JB5.TIF</image>
</page>
</document>
