<?xml version="1.0" encoding="windows-1252" standalone="yes"?>
<!DOCTYPE document [
  <!ELEMENT document   (languageid,page*)>
  <!ELEMENT languageid (#PCDATA)>
  <!ELEMENT page       (pagenumber,text?,image?)>
  <!ELEMENT pagenumber (#PCDATA)>
  <!ELEMENT text       (#PCDATA)>
  <!ELEMENT image      (#PCDATA)>
  <!ATTLIST image      timestamp CDATA #REQUIRED
                       size      CDATA #REQUIRED>
]>
<document>
<languageid>21</languageid>
<page>
<pagenumber>1</pagenumber>
<text>
Tooneel
Muziek
DE OUWELUITJES THUIS
HENRIK SCHOLTE
Harwood's Ds Ouweluitjes Thuis"
bij het Centraal Tooneel
T il K. old folks at home. .. . het is een merk

waardig modern en boeiend stuk van
scherpbeliohte karakteranalyses, dat Harwood
&lt;&gt;ns hier ..a preiulre ou a laisser" voorzet, en toch
een stuk. dat tenslotte niet bevredigt: het bevre

digt zelfs te miniter naar mate men er meer over
nadenkt en het zou het beste &gt;,ijn. het maar een

voudig als brillantc conversatie te nemen en de
snep zoo heet te eten als zij werd opgedi 'lid. . . .
indien dat kon. Daarvoor loopt het stuk er echter
weer teveel de kantjes van at' en die kantjes grenzen
weer aan kleine, dagelijkscho afgronden van gevaar.
wa:u- het duister is en kil en waar illusies worden
omgebracht, alle overtuigingen vermoord en alle
schoonheid geworgd, llarwond is. als zoovele
Kngelsche comedieschrijvers van vandaag den dag.
«•en meedoogenloos analyticus en het deert hem
blijkbaar niet. dat er veel bij kapot gaat wat wij
zelf dan maar weer aan elkaar moeten lappen. .11 ij
iïoeft. zonder eigenlijke these, een pet ie trant e visie
op dri • vrouwenportretten: een keihard, gedesil

lusioneerd jong meisje, da*. ..alle.-; onder de shilling
verkoopt" en vo ••• het beetje sensatie dat haar rest
bereid is den prijs te betalen en zich dus afgeeft
niet jongens, die zij haat ma-ir die huur altha-is den
voortdurenden .prikkel van gevaar geven. ..Met
Steven heb je het gevoel dut je altijd ineens iets
zou kunnen overkomen." zegt Li/a zelf. Het andere
vrouwtje is een schóonzusje. met haar
contrasteerend in methode maar'niet in wezen: zij idealiseert
pathetisch haar zucht tot avo:ituur, typisch klantje
der psycln•-analytici in haar behoefte aan levens

drama's, die /,ij achtereenvolgens zocht in muziek.
in religie, in het moedeisvhap en tenslotte in het
overspel. Boven de/e beiden staat de wijze,
jonggebleven moeder, prachtige vrouw in haar scherpe
intuïtie van een vorig geslacht, d i i -kwart van het
stuk een figuur di &gt; men toejui'-ht. totdat /.ij ten

slotte, met haar beide ontgoochelde kinderen ietwat
beteuterd om haar heen. zelf niet een kleine biecht
komt. ..Och mo'd«T, /.o «iets hebt u toch nooit
gedaan." /eggen d-- dochter* na een lichtelijk
wilden nacht, die min of meer dour de moeder zoo
gearrangeerd was. ,,Dat heb ik wel," zegt de moeder,
en die zin zou voldoende geweest zijn. Het gaat ons
niet aan, hoe een vorig geslacht aan zijn superieure
wijsheid gekomen is en ,,sex is no probleni of the
twentieth century only" zegt Harwood zelf. Maar
dan krijgen wij nog een heel verhaal: de grijzende
diplomaat uit het eerste bedrijf blijkt de minnaar
van de moeder, wat iedereen wel kon raden. Maar
n i -mand wist dat er thans nog heimelijke telefoon

gesprekjes tusst'hen hen bestonden, niemand ver

wachtte het verrassende slot-effect, dat de brave.
wereldvreemde professor met een wijs gebaar van
de. n alleswetenden echtgenoot zijn lorgnet glazen
vegend uit de kanier zou sluipen terwijl du moeder
in een ,,Voix Humaine"-attitude den diplomaat
goede reis naar het verre Indiëwenscht. Dat gaat
te ver, dat ontneemt de moeder haar recht van
spreken en is ,,out-of tone". Zulke moeders zijn niet
de ouwe-luitjes-thuis: zoo zij al bestaan, waren
zij in haar jeugd evengroote uitzonderingen als
thans, zoo zij indertijd het levensavontuur buiten
haar te vroege huwelijk zochten, dan is dat na
twintig jaar tenminste bijgelegd en in effen banen
geleid: zoo zij echter werkelijk den anderen man
liefhad en met den verkeerde was getrouwd...,
wel. dan wordt de leegte achter alles een beetje
erg cru en spookachtig en welken raad kan zij haar
eigen kinderen meegeven?
Het is vooral aan de zeldzaam doorwerkte en
harmonische vertooning te danken, dat tweemaal
twee toch nog steeds -\ier blijft en men dit stuk.
mits men het niet op den keper beschouwt, toch
nog aanvaardt als een modern familiestuk, waar
men desnoods ook nog niet zijn Kerst logénaar toe
kan. Laseur heeft voor een meesterwerkje van
intelligente regie gezorgd, zijn eigen rol als de
lichtelijk vooze romanschrijver was rijk in onder

tonen en geraffineerde details, de moeder van
Tilly Lus was zoo innig bekoorlijk, zoo licht en
zoi» superL-ur gespeeld dat men haar na elke scène
wel zou willen toejuichen om de kleine knock-outs,
die zij uitdeelde. Mary Dresselhuys gaf uiteraard
de juiste hardheid en ,.glamour" aan de rol van
d" society-girl. K ie (ülhuys was charmant, maar
wezenlijk zwakker als de roiuanisccrondc
sohoondochter. Hen pracht van een rol van Krits van
I Huigen in de felle, maar nimmer overdreven scènes.
waarin hij de beest uithing en kKi'ier typewerk van
Schwab (met eeti mooi slot als het goedige profes

sor! je j. Joan Hemmelts. Ludzer Kringa en Chris
liaay. Zoo lang het tooneel zelfs niet geheel zuivere
stukken zoo zuiver weet te interpreteeren zou men
eigenlijk niet van een Uumcelcrisis mogen praten.
want als het publL-k dan nog nl.'t komt. is het
alleen jammer van de menschen en niet van het
tooHcel.
Het Waleson kwartet
CONSTANT VAN WESSEM
O N DEK de Nederlandsche strijkkwartetten
is het Waleson-kwartet, hoewel van vrij
recent en datum, een der merkwaardigste.
Het vereenigt een viertal jonge Nederlandschc
musici, die een hooge opvatting van hun taak
hebben niet alleen, maar die ieder voor zich
kundige en enthousiaste ensemblespelers zijn. Op

vallend is het eenigszins improvisatorische karakter
van hun samenspel of liever gezegd, men krijgt den
indruk, dat. hoewel zij zich als ensemble handhaven,
de spelers ieder op zichzelf zich aan hun
musiceerlust overgeven, waardoor een. boeiend en levend
beeld van het gespeelde ontstaat. Dat hierin ook
.govaren kunnen schuilen en dat vooral de cellist
Hesse zich wat behoort in te tomen, het blijkt, bij
een klassiek werk als een kwartet van Mo/art,
waarin de eerste violist Waleson niet genoeg bleet'
overheerschen en het klankenbeeld door het ver

schuiven der klankverhoudingen wat ongewoon.
te modern aandeed. Maar overigens kan men alle
waardeering hebben voor het voortreffelijke, Waar
toe dit ensemble in staat is, een waardeering, waar

aan reeds uiting werd gegeven door het feit, dat
het Concertgebouw deze spelers een plaats inruimde
op de zes kamermuziekavonden, die onder zijn
auspicia in de Kleine Zaal werden gegeven.
Het Waleson-kwartet kwam Hiterdagavond oj&gt;
zijn. concert in de Kleine /aal uit met een program
ma, dat verre van conventioneel was en dat hei
gemakkelijke succes met de geijkte succesnum
mers versmaadde. Blijkbaar was het deze jong«
musici er meer om te doen, het moderne onder d»
kwartet muziek recht te laten wedervaren en nie'
alleen met den goede wil zooals vaker geschiedt
maar ook door een voortreffelijke uitvoering. Zo.
werd iedere uitvoering een muzikale daad.
ZMO'II kwartet van Milhaud, het 7de, hoe goei
werd het weergegeven in zijn geaardheid van «e»
aangenaam, melodieus en speelsch werk, dat ge
heel gecomponeerd is met de musiceeremle voort
varendheid. die Milhaud kenmerkt. Als schako
met het verletten.diende een kwartet van'Mozart
dat • wij zeiden het reeds geheel in stijl werd
vertolkt.
Na de'pauze ging een nieuw strijkkwartet vat
Willcm Tijper en ik veronderstel, dat de componist.
die zelf aanwezig was. voldaan zal zijn geweest ovc
de uitvoering. Men geniet de muziek van Pijp» •
nu eenmaal meer met het hoofd dan met het haf! :
deze gewaarwording werkt verbluffend wanne» r
men vlak daarop weer wi/ziVA1 hoort als die van h»'
kwartet van Ha vel. waarmee het concert beslot i &lt;
werd. Het kwartet van Pijper had alle kenmerk» t
van zijn talent, vast van vorm, knap ontwikkel» .
zooals gewoonlijk, uit een klein motief. Beschou.v l
men de muziek zooals Pijper dat wenscht, dan nie
dan lof. Niemand in Nederland kan zoo knap • i
Nederlandsche lyriek in zeven platen
D. A. M. BINNENDIJK
ZIJN succes als voordrager van Nudorlandseho
lyriek heeft Paul Hu f indertijd het plan
doen opvatten, de werken, die hij op
zijn verschillende tournée's door ons land heeft
gedeclameerd, vast te leggen op grammofoon

platen, zoodra hem de gelegenheid daartoe zou
worden geboden. Hij heeft daarbij de verleiding
weerstaan, slechts enkele losse platen van zijn
voordrachten te doen vervaardigen: zoowel prij

zenswaardige eerzucht als een gewetensvol veraiit •
Woordelijkheidsgevoel jegens de dichters hebben
hem het geduld geschonken te wachten tot
..Columbia" zich bereid toonde deze,, door Huf mot
groot c nauwgezetheid uitgewerkte, denkbeelden
en projecten te verwezenlijken. Huf's bedoeling:
een beknopt, uiteraard niet volledig maar doel

treffend overzicht t o geven van de .Nedorlandscho
literatuur in haar lyrische verschijnselen, is dooi

de zeven 'platen, welke het licht hebben gezien
zeer goed te realiseeren gebleken. Dat Huf y.icti
Rit Cilhuys en Cees Laseur in débakonscènt in
De ouweluities thuis"
beperkt, heeft tot de lyriek, acht ik volkomen ji
motiveert!. Ten. eerste zou het practisch niet doei •
lijk zijn geweest het pro/a, met name, het romai
proza, in fragmenten tot zijn recht te doen. kornei .
(•en tweede behoeft de poëzie in Nederland, me»;
dan de populaire roman, een'middel, waardoor z j
het volk kan bereiken. Wanneer men tevens hi t
tloel voor oogeri heeft de geheele Nederlandse!1»'
literatuur op deze wijze télaten ,,spreken", dan c
men wel verplicht de poëzie als stof te kiezen, daiu
er lange tijden óf geen prozainliterairenzinis
geschreven, dat zich voor een behandeling als de/f
z»m kunnen leeneti, óf te veel om tot een keu1/&lt;
te kunnen komen. Zoo zijn wij nu in het be/t
van een reeks gedichten, die hun waar«i
in klinkende munt hoorbaar maken. Vuur. «l
inrichtingen van onderwijs, waar de; literatuur
geschiedenis een leervak met-eigenaardige moeilijk-'
heden is. zal deze verzameling platen door ha*r
weloverw» «gen samenhang een onovertrefbaar hul]'•
middel blijken, dat, naast de teksten gebruikt.
het aosthctiseh genot, der bestudeering verhoogt. ^
Het getuigt van inzicht, tlat Huf zijn tekste &gt;
heeft gekozen uit ' de Middcleciiwschèlyriek, ui'
de K'tle en 17de eeuw (liet Wilhelmus, Hooft.
Breoro, Vondel), en dat 'lij daarna direct zijn sprong
zoo consequent wat "Pijper kan. Ik kan het niet
helpen, tlat ik onder muziek iets anders nog versta.
Het kwartet van Ha vel werd een lust voor het
oor, hier kwamen de spelers nog eens extra los.
Na tlit afscheid zeggen wij: tot spoedig weerziens,
en thans niet als een gemeenplaats.
Brieven van Julius Röntgen. Verzameld
door A. Röntgen-Des Amorie van der
Hoeven. H. J. Paris. Amsterdam 1934
VAN den twee jaar geleden gestorven
musicus en componist Julius Höntgen,
Duitschervan geboorte, doch door een meer
dan 5ü-jarig verblijf in Nederland een
deionzen geworden, verschijnt thans een keuze uit
zijn correspondentie met vele personen uit zijn
tijd, brieven, waarin veel opmerkelijk» en aardigs
voorkomt zoowel over Höntgen zelf als over
anderen.
Höntgen was jong in den tijd. dat de musicus.
de uitvoerende musicus het muziekleven
betoekontle. een tijd van een hartstochtelijke
muziekbeoefening. zooals Höntgen zelf zijn geheele leven
lang de muziek beoefend heeft en waarom hij ons
altijd als een verschijning uit dien voorbijen tijd
voor oogen blijft staan. Deze brieven versterken
dien indruk nog meer. wij vinden er ook den
mensch Kontgen geheel en al als musicus iri terug.
In zijn jeugd liyi'ft hij nog Liszt voorgespeeld.
de jongeling zag to.-n reeds de heilige vereering.
di • d" bewomk'iairs voor Liszt hadden niet
zonder vermaak aan: op e:-n soiree bij Liszt.
waarop ieder vtv-1 drukte maakt en Liszt na ieder
stuk, tlat er gospe'ld is. de hand wordt gj-kust.
fluistert de jonge Höntgen zijn moetier toe: ..Je
suis tont ehemin". d.i. de Fransche vertaling van
..Ich hin ganz weg!". (Hij de meesten, die hij
vereerde. Brahms. '(Jrieg. was hij echter echt
..weg"!) Humor vindt men veelvuldig in do/c
brieven, die bijna alle in het Duitsch zijn ge

schreven, een goedige, gulle humor, die ook zijn
muziek kenmerkte, nimmer hatelijk.
Höntgen vertelt veel wat hij beleeft en .ontmoet
tijdens zijn kunst reizen, zijn brieven zijn kennelijk
«ezellige mededeclingen. geen verslagen, en hun
svaarde betreft, naast dingen over tijdgenoot en.
in de eerste plaats het beeld van den mensch
Höntgen. tlat men uit die brieven krijgt en dat
\\ ij ook reeds uit zijn muziek van hem kregen.
De verzani"huus!er deed een keuze uit blieven
aan Höntgen's ouders, aan zijn beide vrouwen.
aan (Jriog. Brahms. Messchaert. Kngolsniann. l'osa.
Stoekhausen. Men mist brieven aan zijn gewezen
partner Casals. die Höntgen zijn ..oudste broeder"
noemde: /.ij gingen helaas verloren.
genomen heeft naar de Tachtigers en de modernen.
Want als hij een poging ha-I, willen doen. óók d,e
hier tus'schen liggende eeuwen te
vertcgenwoordigen. «I.a'i zoutten de a -sthetischo problemen-ontel

baar, zijn -geworden en een oplossing ervan zou
«ii-n schijn van willekeur niet hebben kunnen
vern lijden. De wijze waarop ll'uf zich van zijn. voor:
«I. ra ge rstaak heeft gekweten, is biiven allen- lof.
verheven. Men kan hier en daar van opvatting 'niet
hem verschillen, in het algemeen onttrekt zich zijn
interpretatie aan elke critiek en dunkt ons-ook een
.'afwijkend inzicht .door t'.en tekst zelf gemotiveerd.
Hot heeft geen zin in détails te treden met be

trekking tot de keuze der (lichters of-'gedichten.
Technische eischen hebben enkele malen do lengte
der verzen bepaald en heiligt, voor de hand, dat men
zich te dien aanzien dus van vitterij moet ont

houden. De aard van'do. gedichten' die n
speolkant vullen • houdt,, gewoon! ij k verband met de
bed.ocling van tien voordrager om gelegenheid te
bieden naar aanleiding der teksten een beschou

wing te geven over do opvatting van overeen

komstige motieven bij onderscheidene kunstenaars.
Met. de publicatie van deze 'W gedichten en n
stuk lyrisch proza van Van De ij spel heeft Paul Huf
; niet alleen de -docenten' in do Nederlandsche lit
,•• rat uur. maar bovendien ieder, die beseft, tlat een
gedicht tle eigen vorm en bewoging niet in t'.e
lettertoekefis en de ..actie", maar in 'do
volgzaamJieid van de meiiseholijke stem moet kunnen doen
^Uitdrukken, ten zeerste aan /ioh 'Vorplfoht.

l . • ' ' • •' ' •
Bióscopy
a" uit Onder moeder's vleugels" (Rialto, Amsterdam)
Onder moeder's vleugels
L. J. JORDAAN
Kerstfilm in Rialto
D K eeuwige vraag naar variatie doet de
Atnorikannscho film weer eens opnieuw
volte face maken dit maal mot oen nieuw
genre en een nieuw spelers-type, ('ukoi's ..Litlle
women" gaat niet slechts zonder, blikken of blozen
terug naar de braafheid van de goede l.ouisa
M. ,\lt-ott het brengt ons tevens een ..ster"
wier naam tot voor korten lijd in d" filmwereld
vo'sltigon onbekend was. Hachelijke ondernem-in&lt;j:
in volei lei op/ichten ! Wani geen mentaliteit
schijnt moeilijker te aanvaarden dan die der
iiiidYictorians geen tempo past minder in «n/c
koortsigeii cadans dun &lt;&lt;;it der weloverwogen
burgerlijkheid geen handeling hou»'.1 ons
minder vast dan de tamme belevenissen .van een
provinciestad anno 'tJO.
Ziohi -r dan do vier ..l.ittle women" van A loot'.
in hun vreedzaam, ietwat bekrompen gedoe, van
meisjes uit tle crinoline-periode in hun kleine
conflicten, bescheiden aldags-zorgen on weinig
hartstochtelijke amoiircuso perikelen. Kon
«enegenhoid voor oen buurjongen een zusje dat
sterft' --. oen scntimontoolo Kerstavond 'wat
vage schrijfsters-aspiraties bij oen dor meisje s. ...
langs dozo niet bepaalt! opwindend'' avonturen
kabbelt do levensstroom, tier fami'ie. die eigenlijk
de ..heldin" van tl»%zo film word. voort. Mol als
groote evenementen dan o^n hèp.'seho ..trip t o
Kurope" on oen verren oorlog waarvan het geraas
nauwelijks tot dit milieu -doordringt. Nog eens:
welk een hachelijke ond"rncming! Maar ook:
wolk oen succes voor tle makers !
Want wel zelden word oen historische sfeer /ooi
intens doorleefd als in dozo film z»ldcri ook
wist feu twintigsle-oonwer zjch zoo te verplaatsen
in do mentaliteit oonor vroegere generatie. Nog
onlangs zag ik te Parijs hot zeer knappe ...Madame
Uovary" van Joan Henoir. tlat' met al zijn
kwaJiteiten oen koel, 'decorstuk bleef, bekeken niet
do nuchtere, nieuwsgierige oogon van onzon tijd.
..Little womoti" daarentoge,n brengt tle sfeer der
crinolines on rnodoratourlampon als oen lovende.
vibroorondo werkelijkheid. In .dozo mot liefde on
smu'ak goarrangeordV wereld dor ..sixties''. voelt ,
men don heiligen '•schroom voor hot h'oftige on
extravagante - do-oorlijko zelf-vortootloring voor
hot bravo on sentimentoolo als itjts natuurlijk^ on
reeels. . . . zooals hot voor d-- t ijdgonootoii moet
zijn , geweest.- Ik hel) mij afgevraagd, de/e film
ziende, hoe hot mogelijk was oen \erhaal als dit.
vol l'u* iel, goboiiron. vol convent ioiieele braalh'id.
vol sentimentaliteit niettemin tot een t'ris-h
en nimmer vervelend relaas te maken, liet wil
mij tenslotte voorkomen, dat het dit famoiise
d &gt;&lt;'rd'i'igon in den tijdgeest is. wat oen dergelijke
to'ilisitic mogelijk maakte. Alloen do filmer di •
y.i'.'h 7. &lt;n vovoonzolvigi, met. de historische sfeer.
d.-it hij zelf gelooft in de belangrijkheid van al dit
kleine yotloo is in staat de conflicten in
«lezen niikrokosmos hun mon^clielijko waarde te
g«-Voli.
Aldus werd ..Litt Ie'wonion" een het is waar:
soms wat lant;o. maar nimmer onbelangrijke of
vervelende historie. Kon klaar, sterk on simp-1
verhaal, «bit midden in zijn romantische conventie
s uns verrast door ..moderne" aarzelingen en
oitovonwirh- ighct'on in hot karakter van ...To".
«!&lt;• wüd'-bi-as dor fiimili.-. Tus-ichen de wat tvage
tyroii.tlor dvio a'ideiv zusjes staat dozo merkwaar

dig s! rak g«'toekende nr'isjosfigui'r alloen
wtmderlijk siamgogio id me! den tijd. in haar, bijna zieke

lijk f'tmi i 'p'.yii.'l. tloch tevens vol van do onrust
oii «l-- oj s'uM«iigh&lt; id. waaiin /.ich oen ni.-uwe
toekomst aaiikontligt. .Hot is Kathoupo Hepburtï.
die in deze tol vuör Notlorlantt debuteert en naar
tnijn tneoiiing althans 'mei vlag en \yimpol
hot pleit wint.
Welk oen temperament Welk i'.-n frischheid
«*n natuurlijkheid on daarbij: welk een eenvoud
in middelen staan do/o filinspoelstoi- ten di -nste !
'Vaüdo ietwat houforige gratii'. waarnioo haar
jongonsfigunr «l.&lt;* typiscli-vrttuwolijko •h'oopolrokkoii
tlraagt. tot de schiichtoro innigheid van blik en
gebaar, is allesCcht en warm on lovend aati tleze
'...Jo". Hot vreemde «'onflict 'tusscheti t'on bijna
mannelijke hranio on het lood/vvuro bes.'f van het
..onvoegzanu?" doiv.olvt'. maakt tlit
suFfriig'otteembryo tot oen d-aina op/ichzolf, waaraan
Jlepburn al do verve van haar buitongowo:»n talent
weet to geven. Kr i.-* geen twijfel mogelijk: zij is
do ..ster" van «leze-opmerkelijk knappe film. ...
maar hot zeldzame is daarbij, dat /ij tlit in geen
nkel1 opzicht i accentueert. .Mot ,aI haar
bliitongowono begaafdheid blijft zij binnon hot kader
«lor compositi-: ^i'-n der v i -r zusjes. Zoowol voov
PAG. 6 DE GROENE No. 3002
PAG. 7 DE GROENE No. 3002

</text>
<image timestamp="2002:11:06:19:47:19.00" size="673015">D3000JB0.TIF</image>
</page>
</document>
