<?xml version="1.0" encoding="windows-1252" standalone="yes"?>
<!DOCTYPE document [
  <!ELEMENT document   (languageid,page*)>
  <!ELEMENT languageid (#PCDATA)>
  <!ELEMENT page       (pagenumber,text?,image?)>
  <!ELEMENT pagenumber (#PCDATA)>
  <!ELEMENT text       (#PCDATA)>
  <!ELEMENT image      (#PCDATA)>
  <!ATTLIST image      timestamp CDATA #REQUIRED
                       size      CDATA #REQUIRED>
]>
<document>
<languageid>21</languageid>
<page>
<pagenumber>1</pagenumber>
<text>
Beeldende kunsten
fel
fit'
Tooneel
Ge/e koorts." Van links naar rechts: H. Corpentier A/ting.
A/6. von Do/$um. /. Stern/ie/m. Frits van D»jk en Ben Royaards
EEN DRAMA ZONDER STUK
Henrik Scholte
Sidney Howard's Gele
Koorts" b/d Amsterdam

sche Tooneelvereenigmg
DAT er aan het boerin van de/e
eeuw in «• -n klein ..\rnei ikaans -h
leg.-rkamp op het pas
verovev1 de Cuba daden van ongehoord»'!! durf
• •n h«-ldenm«:ed ver. i-ht zijn. die met
de eigenlijke l'' et i:lg val" »l»'ll
kl'ijusnian ni.-ts te maken haiid.-n: dat op
y.oek naar d-- oi&gt;rzaken van d&gt;- des

tijds in heel Middel-.\mei-ika zoo
^'.•Vlês Ie u«-le koort S. (lic meel'
Amel'ikaanseh*- soldaten t«-n ta\«-
s!.-i-j&gt;t«dan &lt;!•• uaMsche kiijir teucn
Spanj»kostte »-n «lie /eVeii jaar te voren d^-&lt;
werk/.H'imbeden aan het half voltooide
l'anama-kanaal lam gel»'g«l ha«l.
«hlfd.-n-d"kton-n van «Ie x,.u'. Y«-llow
Kever ('oinmissti&gt;n hunne bevoegd

heden Vel- ov«-!S hfedell ell bij yyhrek
aan «-enig vervangbafii- &lt;li -i-lijk
maleriaal • zichzelf en een aantal vrijwilli

gers als pr«.&gt; -fkonijt.it jes gingen besmet

ten, waarbij slacht of fel s een
viveselijk»-!- maar tevens een heroïscher
••n nuttiger dood. sti Tven'-dnii die
op het slagvell: dat in dat kleine
legérkamp tenslotte'ontdekkingen ge

daan werdon, die d" menschheid sinds

dien in wezen van den geesel dier
tropische ziekte bevrijdden dat
alles zijn feiten, die. gelijk de meeste
medische held'-ndarlen. niet in bal

laden en melodrama's bezongen zijn
»,-n derhaUe hun gio )ts'.e waarde
«•ntleenen aan d&lt;; ongewone
mededeeling, aan hun betrekkelijke infor

matieve primeur.
Zeker, men vindt ze in dat merk

waardige boek van Paul de Kruyff.
..The Microbe Hunters", men vindt
daar de korte, hevige tragedie van
het Cubaans ?ht*' kamp met een
suggestiviteit beschreven, die zonder
twijfel Sidney Jloward aanspoorden
«•III ej- 'ook IH't; een \ • &gt;&lt; ilieelilrania van
ti- inaki-n: een drama, «lat all'- luimen
dl l'eitell aan lu-t gvsclm-veti verliaal
ontleend»- en er niets anders aan toe

voeg-de »lan tien naam'valt een /ekereii
Siilney llow.ml naast dien van /ijn
medewerker l V Kruyff. Want Cen
ii,;tn-"&gt; M uk werd ei niet van gemaakt
••n //MI hot drama op de planken iets
toevoeirde aan het gvscliroveii drama
in bet eenvoudige pro/a van ..The
&gt;Iii-i-obe . IIunt«-i's." dan is die t
oevoegiüu slechts te vergelijken met do
/.uiver realist isehe illustratie van «ilk
willekeurig boekwerk: men y/ig thans
dat de onstuimige, jonge doktor
; Jesse La/.oar. naar w ion de
Amerikanoii later in de haven van Ha
timore een kust batterij not-inden, «-on
baar«l droeg- on «lat Walter lieed
pr«-i-ies liet vriendelijke, /aolite
ge/icbt bad dat l'aul «Ie Kruyff in drie
woorden bosohreof. \'ordei- gaf
«l»«Iramat i/eerinjr niets wat niet- ook
anders en beter 'bekend gemaakt
kon woi-den. Kr word liiets we'/on l ij k
g»;croëenl on do emoties, in den
t»toschouwer opgewekt, liggen /uiver
in do.meegedeelde.feiten en niet in de
uiterst mediocre schepping van het
..tooneel"'. dat het tenslotte immers.
'zou moeten hebben van een bepaaMe
•her-vorming der waarheid in het licht
eener synthese en niet van een volks

universiteit-lezing met lichtbeelden.
hoe boeiend, hoe groot het onderwerp
dier lezing op zichzelf ook zij.
Er werd. na de voortreffelijke en
soms zelfs magistrale voorstel ing
door de Amsterd imsche
Tooneelverecniging, die zich uitgesloofd had
in scenische effecten en in bezieling
van voordracht,, een openbaar debat
gehouden, waarin soms aarzelend,
soms te scherp en te
gemakkelijkgeneraliseerend, deze zelfde bezwaren
tegen het stuk naar voren wei-den
HABANOLA
DE SIGAAR VAN STANDING
Fabrikaat: VAN DER PUTT &amp; DEVLAM - EINDHOVEN
Over de kritiek der
H K'r schijnt mij toe. en dal is
di- aatil. Hing tot dit opstel.
dat in de besprekingen dor
Vl is'.ischc kunsten dr
»&gt;n»lui»Iolijkhodon. do vangheden en de
oir/.uiverh» i l y.oo groot werden, dut y.e niet
\v«&gt;l meer worden verdragen. Natuur

lijk /al ik niet ontkennen, dat er
kundigon en onkundigen onder
«hkritici /.ijn.lk y.ou vervolgens kunnen
vaststellen, en hoe menschelijk is
dat! dat voor sommige schilders die
kritikus alleen kundig is. die hun
werk prijst of prees en het ruim

schoots «-er gal'. Wanneer ge weet
met hoeveel r&lt;~/-'/('«"/«r//»' toewijy.ing
sommige levens gevuld /ijn en niet
hoj hardnckkigon hartstocht vol

gehouden wordt, waar -het beter was
nooit begonnen te /ijn. dan y,ou u als
mij dit alles niet bevreemden. Maar
toch n ding is noodig: de
onwerkelijkheden vast te stellen. Deze
schaden: baten nooit. Kriti.-k is niets
anders dan hel schiften van werkelijks
• •n omverkelijks. van wat baat en
wat' schaadt: /.ij is dus noodzakelijk:
een functie van elk georganiseerd
leven, dus ook van het onze. . . .
Mijn .bezwaren tegen de kritiek van
velen zijn. .zooals ik zeide. van zulken
aaid. dat ik ze hier wil openbaren.
Ken kritiek -van schildeikunst (en
d;it is tegemvooidig munt-tikt lijk te
/egp-it ! i lijkt mij toch ten eerst»- het
over schildei kunst te moeten hebben.
zooveel mogelijk daarover en zoo
zuiver mogelijk daarover. Voor het
wedeizijdsch 'Wel verstaan, is het
ten eerste noodig. dat we van bepaald

heden uitgaan: van bepalingen, waar

over wij het ns weiden: we kunnen
dan. desnoods niet eeii half woord
verstaan. Ik weet. dal behoef ik toch
niet te zeggen, dal er iets is. dat
voorafgaat aan 'elke bepaling: de
kritikus moet gevoelig zijn voor de
symbolen der schilderkunst, voor de
hoedanigheden der lijnen van de
teekenkunst. \ oor lre\ niodel'éder
beeldhouwkunst, voer de
rhythmische -stapelingen der vohimina. Pat
, is het eerst »•£, «lat li'oschi -»lt bij
sommigen zwijgend. [)e kritikus is «'e
spreker van vele /wijdenden: hij moet
dus behoorlijk zich" kunnen uitdruk

ken. Jlij moet. «nik «lat is natuurlijk !
een gcrneenzamen grond van ver

standhouding hebbeti gevonden: hij
moet bepalingen, hebben, waai op hij
steunt en waar»ip de anderen mee
zullen steunen. Zulke bepalingen
outALBERT
breken te velen kiitu-i of zijn hun niet
geme«'nzaam genoeg. . . .

Tegenstanders
W I.' allen hoorcn. in de kunsten.
WeJ. eens van realisme en van het
romantische, maar «Ie meesten blijven
«leze dingen in hun omlijningen vaag
en ver. Toch berust op het inzicht
«laarvan n der hoofdverdeclingeii
dor schilderkunst en niet der schil

derkunst alleen! (.ie kunt gerust,
zonder overdrijving, -/eggen, dat
metde woorden. ..realistisch en roman

tisch" de twee eeuwige tegenstanders
in de kunsten zijn aangeduid. Laten
wij dit hier. zo«&gt; ergens ! nauwkeurig
bepalen. J Iet schijnt mij dan toe.
dat wij kunnen zoggen, «lat het realis

me «Ie bekentenis der veelheid, der
verscheidenheid is en dat het roman

tische is «Ie bekentenis der eenheid.
wat de • verschijningen aangaat. Ken
realist is «lus hij, di«« «Ie verscheiden

heid der 'dingen t«-n eerst»' ervaart:
een romanticus is hij. die een eenheid
achter «te «Ü!»g«'ti voelt en «lat moet
bekennen. In de s •hilderkunst moet
«lan. v«-l'*&lt; ns d" «-is -hen der
sehilderku'ns'. zulke vcischt i lenlu id of zulke
•eenheid worden uitgedrukt. Dat ge

schiedt «t« or /./ie/1. Ken .realist zal de
vei s -h» i 'lo'ihcitl «Ier dingen
logisch»-!-wijze uit moeten drukken door
v«-rs« hcidcnhi i«l dei kleuren: hij zal dus
'm «h-u pi'-turaal-tc'-hnischeii zin t «-n
intnfifit zijn. Ken romaiitieus «laaren

tegen, die «Ie eeiihi id en de gemeen

zaamheid i&gt;nd«-rling «lei-
veisehijningeii ei-kent. zal zijn ..kleur" zooveel
mogelijk »'•»'• n moeten houden, hij /al
dus vanz'elve neig n naar het een-.
kleurige zij «lat ook geschakeerd:
naar het inonoi-hmnie zal hij van
/elven gekirerd zijn.
Wanneer wij d«- uitingen dei- schil

derkunst onl'evangen nagaan, zien wij
dan ook de twee door mij
aangeduid*typen meest beurt
elings-overheerschend «tpt reden en daar het rea'isme
de metst eenvoudige voorstelling «lef
wereld is. vinden wij «'«-n it-alist. d»Mi
&lt;-o!o|ist liet meest op Onzen 'Weg J
Maai-, en «lit ter voorkoming van
dogmatische eenzijdig!)» id ! er zijn
tu.-s-.-h»-!! «Ie '..typen" tusschonstatcii.
tusschento«-staiiden. overgangen. Wij
vinden die «&gt;ok in de schilderkunst
tusschen het typisch-realis'isL-be en
gebracht «'n het typeert «Ie intuïtieve
opmerkingsgave der jeugdige -toe

schouwers, dat zij allen voelden, dat
dit «jok, zonder aan formalistische
'of. Aristotelische begrippen.' vast- te
houden tenslotte gén tooneel
was. maar slechts de vorm van het
drama gekozen voor mededeelingcn
van informatieven en suggestieven
aard. Geen kunstenaarshand is in
deze rommelige hoeveelheid taf creolen
aan het werk geweest. Indien Mr.
Jloward, lezende over Walter Reed
en zijn vrijwilligers, zich zoo getroffen
voelde dat hij na Paul de Kruyff
opnieuw naar de pen greep, dan had
hij daartoe niet meer fantasie dan
iedere willekeurige lezer dezer helden

daden, want de incontinente
rhapsodie, waarin ons deze historie nog
eenmaal verteld werd. geeft hem
•allerminst het recht om zijn naam
voor dien van De Kruyff te plaatsen.
Hoeveel beter heeft deze .zonderlinge
dichter in simpel, wetenschappelijk
proza het dan getroffen toen Sinclair
Lewis zijn informatie-materiaal ge

bruikte voor ,,Arrowsrnith" en er Wel
e«&gt;n nieuwe eenheid, een waarlijk
kunstwerk ontstond, heg ..Yollow
Jack" naast .,Mon in White": een
s.tuk." dat geen enkele nieuwe
informatie over de medische wetenschap.
maar w&lt;4 een eisen
dramatiseh-eniotiojieele attitude in Schnitzleriaanschen
trant bracht en gij hebt het verschil
tusschen waarlijk U;oncel en de opper

vlakkige paraphrase van een in zijn
historische waarachtigheid streng dra

matisch feit.
Wat intusschen niet wegneemt.
dat men alle bewondering dient te
' hebben voor de wijze waarop Defresne
als regisseur en vele van zijn spelers,
Frits van Dijk, Ben. Royaards en
Albert van Dalsum vooraan, nog
naar zooveel mogelijk plastiek in de
prent zochten en met tal van gemoti

veerde effecten, op een voortreffelijk
gebouwd tooneel. voor een voorstel

ling zorgden, die boeide.... boeide.
naast het feit zelf. om de soberheid
en de eerlijkheid, waarmee hier naar
een heroïsche weergave getracht werd
van een drama der wetenschap, dat
op zichzelf in heroïek niet zijns gelijke
heeft. Kn dat het als zoodanig, na hel
proza van De Kruyff, nog eenander
apparaat ter verbreiding van zijn effect
verkregen heeft., daarvoor kan men
dan tenslotte de Amsterdamsche
Toonoelvereeniging oprecht dankbaar zijn.
schilderkunst
PLASSCHAERT
het typisoh-iontant ischc. Maar ilut
is van la t eren zorg !
\Vamieor wij eenmaal te samen het
romantische en het realistische aan

nemen, zooals ik het definieerde, dan
is reeds een breed e. vrucht dragende
verstandhomling mogelijk. Maar er
is meer en er is meer in y.ulke
. richting bereiklmnr.

Impressionisme
WAT verstaan wij toch preeies
onder imiinHttinni.tim'ï(!e
zultzeggen: dat is een trant van schil

deren, een trant van y.ien maar
i'i'ti triinl run zit-ii /'* bij ilcn nrliilili r
ci&gt;n Ininl run zijn. Dit laatste zuudt
ge kunnen vergeten: g«&gt; vergoot
\velI licht juist dat. (ie meendet voldoende
u zelve in te lichten door bij het
iiiijM'ossioiiiMMo te «lenken aan iets
van voornamentlijk-mannalen ra-«l.
aan een bepaalde bewegingslust van
de hand. maar en het is steeds
weer noodig/ulko dingen te herhalen :
elke trant van schilderen is een
leveiisinzicht. een bepaalde
wa;irdeeringsschatting van hot leven.
liet impressionisme gebruikt
ongetwijfeld een nfH'nhiin-tl. \lieteinleli
l ra vit van schilderen, maar dat komt
daaruit voort, dat &lt;!&lt;• schutter het
leVeli zelf als een niet-st ilst aan	tl
vlieten voelt, als een voortdurend.
onophoudelijk vergaan en verdergaan:
dat zulks hem het eigenlijk leven is
en «lat voor hem. den schilder, all^s
bestaat //ree!» groot e betveging.
Wanneer wij «Ut tezairienuanneinen.
hebben de kritikus en «Ie Ie/er \\vt-r
• •en overeenkomst meer gesloten. Wij
weten da-n hoe een schiltleiij /.al
ge.schiMerd zijn. «lat wij
itnpivssionistisch heeteii. zij het sti«-l gemaakt
niet den heeteii drift «lei- spontane
ontvoering als hulpvaardig helper.
y.(\ het. Jang/aam opg«-vo'er«l totdat
hier noodzakelijke. omveei st aai'ba ai'
vlieten, «lat ik ook ..den bries van
het leven" heb geniM'ind.
Kik ding kent zijn tegenstelling:
daardoor bestaat bet voor de rede.
liet impressionistisch sehildi rij vindt
zijn tegenstelling in het
iirrhili'klnni.-o-lt ftrhiliirrij.' Dat is niet het schil

derij, «bit noodzakelijkerwijs als onder

werp een uiting der architectuur heeft.
een bouwwerk of iets dergelijks, maar
het is dat schilderij, dat de verschij

ningen groepeert tot een /eer.vnst.
nnJclijk rcrhan'tj. waar alles bij voor

keur staat en niet vliet: waar alles
stellig-verbondcn. onbeweeglijk is ten
opzichte van elkaar; waar de natuur.
«Ie figuur, de dieren, de al «»f
niotbewolkto lucht, het vlakke of
niet-vlakke water, als een gebouw wer«l
opgetrokken, volgens een ordenende
wet. Alle toevalligheid? die dikwijls
de schoonheid is van een impressio

nistisch werk wordt noch erkend,
noch aanvaard; alles is definitief.
Het schilderij is oen gekristalliseerde
groep van verschijningen. Wanneer
zoo'n schilderij de spanning na het
«•rdenen mist, niet een betrouwd en
tot orde geworden leven werd is het
niets dan een deftige leugen, een ijdele
^ . groepeering, een demonstratie van
den geest, die valsch en hoogmoedig
is. Is het echter schoon-gclukt. dan
heeft liet van de eeuwigheid der kunst,
de levende rust aan zich, in zich.
Heeft de kritikus'zijn'lezers van
«leze eenvoudige en daaroni moeielijke
waarden weten te overtuigen • hoe
rijpo en rijke .verstandhouding werd
«lan mogelijk en hoeveel' wederzijdseh
verstaan kan daaruit'worden afgeleid !
Heiden leerden zij oen zelfde .\-H-C-.
Over verschillende andere dingen,
waarover zij het eens kunnen worden
in oen volgende' bijdrage.
^^^—Jt
Tango 25 ei
\vora
30 et
20 STUKS
Wat is een man zonder Laurens? Een Kerstboom
zonder lichtjes en engelenhaan Daar is niets
feestelijks aan. Daarom met Kerstmis: Laurens voor
iederen' man! En aan eiken boom Laurens' mooie,
groote doozen Tango, Ivora en Rouge!


LAURENS
Kunsthandel j. Vermeulen, Keizers

gracht 520, 17e eeuwsche Hollandsche
en Vlaamsche meesters.
Kunsthande' E. J. van Wisselingh,
Hokin 78 80. Aquarellen uit het nagelaten
werk van M. A. J. Bauer.
Kunsthandel Aalderink, Jacob van
I^énnepkade 55. -Werken van Chris
Beekmaln. Tot 28 Decembei.
Kunsthandel Fetter,Weteringschans70.
Schilderijen van L. W. R.Wenckebach.
Tot 20 December.
Bovenzaal, Westeinde 25. Schilderijen
en aardewerk van Dirk Q.cker en
(1. J. Lnn«H»y. T«.t 29 December.
Kunsthandel van Meurs, Keizersgracht
578. Oud-Japarische Surimono's. Tot
l Januari 1935.
Kunstzaal van Lier, Rok i n 120.
OostInd. inkt s!'hil:lerijen door J«'llo
Troolstra. Tot .rnimari.

Sted.Museum,('e«-hoslovak.s&lt;-heTyunstnijverhe'id.
Kunsthandel Santee Landweer,
Kei/ersgracht l(!.'ï. Werken van J-'ekmanon
Albert I.oots. Tot ó Januari.
Kunstzalen A. Vecht, Hokin
122.Schild«'rij«''n en ceramiek van Piet Wiegman.
Weefsels van Janna
WiogamnFormijne. Tot 15 Januari.
Parkhotel, 9e Gt'oepentcntoi&gt;nstelling
van Xederlandsche .Kunstschilders.
Tot l Februari.
Den Haag

Kunstzaal 't Center, Toreiïstra-at i 10.
SchiMcrijen. -Tot 28 December.
Kunstzaal Kleykamp, Schilderijen van
Ger. P. Adolfs. Tot 23 December.
Kunsthandel Vincent", Biklersstr. 09.
Werken van Lucie van Dam-van
Issolt. T«;t l Januari.
Huize Statenlaan 71. Werken van
Ida E. Siewertsz van Reesema-, Tot
10 December.
Wei-ken van J. P. v. d. Leeuw.
Tot (\ Januari.
Succeshuis, Koninginnegracht 11 b.
Tentoonstelling van drukwerk. Tot
7 «Januari.

Utrecht

Voor de Kunst", Xobelstraat- 12.
'Kinderp«&gt;rtret.teii. samengesteld uit
een groot aantal schilderijen,
teekeniu&lt;j;eii «*n beeldhouwwerken door
kunstenaars van vroeger enyan «&gt;nzen
tij «l. grootendeels uit Utrechtsch
parti. culier bey.it. Foto'^v.an kinderen door
S. Xijhoff. Tot o l December.
Nu nog even, voor de Feestdagen, een nieuwe
kaplamp voor de huiskamer van Jaspers op de Cein

tuurbaan. Een geweldige en aparte collectie.
JASPERS CEINTUURBAAN 308
Te l of. 21(10» r n JMT4O
PAG. 16 WINTERNUMMER No. 3003
PAG. 17 WINTERNUMMER No. 3003

</text>
<image timestamp="2002:11:06:21:51:16.00" size="584372">D3000JB7.TIF</image>
</page>
</document>
